### ISSUE TITLE
multi-stage build tags old image / uses cache incorrectly

### ISSUE THREAD

**Issue by ansemjo** [containers/buildah#1179]
**Description**

I am building an application consisting of frontend and backend into a single container with a multi-staged Dockerfile, where the last stage simply copies files from the first two stages. I am using rootless `podman build` to build my images. These images will later be deployed to a [flynn](https://flynn.io/) cluster.

**Steps to reproduce the issue:**
1. have a multi-stage dockerfile with a final stage which only depends on intermediate stages (example appended)
2. build the image with `podman build -t app:1.0 .`
3. make changes to your app sources, i.e. new version: `2.0`
4. rebuild the image with `podman build -t app:2.0 .`
5. check `podman images`

**Describe the results you received:**
The new tag `app:2.0` was tagged on the old image. The build did __not__ use caches for the first two stages since the sources were changed. However __all__ build steps in the final stage used the cache, thus the built image is the same as the old tag. I have two untagged (`<none>`) images built, which I suppose are the intermediate stages.

```
$ podman images
REPOSITORY                              TAG                IMAGE ID       CREATED             SIZE
<none>                                  <none>             fd181c7fbfc0   40 minutes ago      382MB
<none>                                  <none>             5e0e119512d3   43 minutes ago      743MB
localhost/batchcards.js                 2.5.3              269aa8e1878e   About an hour ago   105MB
localhost/batchcards.js                 2.5.2-1-g0d5a57c   269aa8e1878e   About an hour ago   105MB
<none>                                  <none>             45a39d3e6440   About an hour ago   382MB
<none>                                  <none>             f921bc100c63   About an hour ago   743MB
```

**Describe the results you expected:**
The final stage should detect that the first two stages are different and not use any cache.

**Other notes:**
I have two other (unrelated) observations with multi-stage builds:

- `buildah` does not accept `ARG`s before the first `FROM`. With Docker you could make the image used in `FROM` an `ARG` itself, i.e. when all three stages shall use `FROM node:10-alpine` you could use: `ARG IMAGE=node:10-alpine` and `FROM ${IMAGE}` instead.
- If the last stage uses the `AS` keyword (i.e. `FROM node:10-alpine AS runtime`) the built image will not be tagged at all and I will just have a bunch of `<none>` images.

---

**Output of ~`rpm -q buildah` or `apt list buildah`~ `pacman -Qi buildah`:**

```
$ pacman -Qi buildah
Name            : buildah
Version         : 1.4-2
Description     : A tool which facilitates building OCI images
Architecture    : x86_64
URL             : https://github.com/containers/buildah
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : ostree  runc  skopeo
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 19.82 MiB
Packager        : Bartlomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Fri 12 Oct 2018 07:14:51 CEST
Install Date    : Sun 14 Oct 2018 03:13:22 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.4
Go Version:      go1.11.1
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      608fa843
Built:           Fri Oct 12 07:15:44 2018
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
$ podman version
Version:       0.11.1
Go Version:    go1.11.2
Git Commit:    "7be2951a9726c2dd811d3b6769ef63b81b808ca7"
Built:         Sun Nov 11 14:52:23 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
$ cat /etc/*release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Output of `uname -a`:**

```
Linux thinkmett 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ cat /etc/containers/storage.conf | grep -v '^#' | grep -v '^$'
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
mountopt = "nodev"
[storage.options.thinpool]
ostree_repo = ""
skip_mount_home = "false"
```

---

**multi-stage Dockerfile**

```
# build the frontend dist
FROM node:10-alpine as frontend

USER node
COPY --chown=node frontend /src
WORKDIR /src
RUN yarn build:prod

# build the backend dist
FROM node:10-alpine as backend

RUN apk add --no-cache -t build-dependencies \
    g++ gcc make musl-dev python

USER node
COPY --chown=node backend /src
WORKDIR /src
RUN yarn build:prod

# assemble final runtime container
FROM node:10-alpine

WORKDIR /application
COPY --from=backend   /src/node_modules   ./node_modules
COPY --from=backend   /src/package.json   ./package.json
COPY --from=backend   /src/.sequelizerc   ./.sequelizerc
COPY --from=backend   /src/dist           ./dist
COPY --from=frontend  /src/dist           ./static

USER node
CMD yarn migrate && exec node dist
```

**Comment by ansemjo** [comment]
A minimal project to reproduce the issue:

## files

### Dockerfile
```
FROM alpine AS uuid
COPY uuid /src
RUN cat /src/data

FROM alpine AS date
COPY date /src
RUN cat /src/data

FROM alpine
COPY --from=uuid /src/data /uuid
COPY --from=date /src/data /date
CMD cat /uuid /date
```

### makefile
```
.PHONY: rand
rand:
	mkdir -p uuid
	uuidgen > uuid/data
	mkdir -p date
	date > date/data

VERSION:
	echo 0 > $@

.PHONY: incr
incr: VERSION
	echo $$(( $$(cat $<) + 1 )) > $<

.PHONY: image
image: incr
	podman build -t test:$$(cat VERSION) .

.PHONY: run
run: image
	podman run --rm test:$$(cat VERSION)
```

## usage

Create random data ("source code"):
```
make rand
```

Build, tag `:1` and run the container:
```
make run
[...]
STEP 4: RUN cat /src/data
7d42ea11-e6c5-41fc-8ba7-baaff02aae30
[...]
STEP 9: RUN cat /src/data
Thu 15 Nov 15:06:26 CET 2018
[...]
STEP 17: COMMIT test:1
podman run --rm test:$(cat VERSION)
7d42ea11-e6c5-41fc-8ba7-baaff02aae30
Thu 15 Nov 15:06:26 CET 2018
```

Create more random data ("change the source code"):
```
make rand
```

Build, tag `:2` and run the container:
```
make run
[...]
STEP 4: RUN cat /src/data
0f752de2-4992-4c3d-9f95-a796f3509bef
[...]
STEP 9: RUN cat /src/data
Thu 15 Nov 15:09:08 CET 2018
[...]
--> Using cache f0f217d91216d13013d9d1fb0f4c73f10616e59601ba1649ef689521d69daf86
STEP 17: COMMIT test:2
podman run --rm test:$(cat VERSION)
7d42ea11-e6c5-41fc-8ba7-baaff02aae30
Thu 15 Nov 15:06:26 CET 2018
```

```
$ podman images
REPOSITORY                              TAG                IMAGE ID       CREATED              SIZE
<none>                                  <none>             44466c4181fa   About a minute ago   4.68MB
<none>                                  <none>             c1533837329e   About a minute ago   4.68MB
localhost/test                          1                  f0f217d91216   4 minutes ago        4.68MB
localhost/test                          2                  f0f217d91216   4 minutes ago        4.68MB
<none>                                  <none>             fcb6f2358c46   4 minutes ago        4.68MB
<none>                                  <none>             b499a7046d88   4 minutes ago        4.68MB
```

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 any thoughts on the cacheing issues here?
@ansemjo Thanks for the very thorough issue report!  If you've time, could you try this using the latest upstream Buildah from GitHub?  I know at least the ARGS commands should work there and there's been a number of caching/storage issues solved there that might also help the other problems that's you've listed.

**Comment by ansemjo** [comment]
I'll try that later today, yes.

**Comment by umohnani8** [comment]
@TomSweeneyRedHat looking into it.
@ansemjo does step 3 mean that you are changing the base image in the first two stages on the second run?

**Comment by ansemjo** [comment]
Not the base image but the source code that is copied into it. I.e.:
```
USER node
COPY --chown=node frontend /src
WORKDIR /src
RUN yarn build:prod
```

I'm copying source code from the subfolder `frontend` on the host into the container, switch my `WORKDIR` to it and build it inside the container. Those steps work fine, since `buildah` properly detects that their context changed. Specifically, I am using git submodules in my project and I am checking out new tags ("change the source code"). The demo in my second comment shows that it is not specific to git submodules though.

**Comment by ansemjo** [comment]
I'm using a `buildah` built from git now:

```
$ buildah version
Version:         1.5-dev
Go Version:      go1.11.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      dac78199
Built:           Thu Nov 15 17:12:31 2018
OS/Arch:         linux/amd64
```

Running the exact same steps as in [comment 2](https://github.com/containers/buildah/issues/1179#issuecomment-439052764):

```
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ ll
total 8
-rw-r--r-- 1 ansemjo users 205 Nov 15 17:14 Dockerfile
-rw-r--r-- 1 ansemjo users 301 Nov 15 17:14 makefile
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make rand
mkdir -p uuid
uuidgen > uuid/data
mkdir -p date
date > date/data
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make run
echo 0 > VERSION
echo $(( $(cat VERSION) + 1 )) > VERSION
podman build -t test:$(cat VERSION) .
STEP 1: FROM alpine AS uuid
STEP 2: COPY uuid /src
--> bb9496e106cc7ec7ffebae0bb00c745195e0acb0237c122d2de44edbcc09c0aa
STEP 3: FROM bb9496e106cc7ec7ffebae0bb00c745195e0acb0237c122d2de44edbcc09c0aa AS uuid
STEP 4: RUN cat /src/data
2ad67301-5855-4eb3-9d91-7f8761e0fc7b
--> 42fa3dcc5492296003d801456eef759324636d66e69da86f5a46ef4acb241a4f
STEP 5: COMMIT test:1
--> 24900ea9a628df70ae00b06ba2d2ca0511ff40da6db3a40b32100ded7e2235ca
STEP 6: FROM alpine AS date
STEP 7: COPY date /src
--> 0fdd3bc242eb2cf44f63df7649cb182b10bf447d14c77a2e385faa2cdec5a4f0
STEP 8: FROM 0fdd3bc242eb2cf44f63df7649cb182b10bf447d14c77a2e385faa2cdec5a4f0 AS date
STEP 9: RUN cat /src/data
Thu 15 Nov 17:17:36 CET 2018
--> d3814fa44bee134d47f59b2e08d0f458d134316f8f7fe9da705be8513c916aa9
STEP 10: COMMIT test:1
--> b1732031b598d403177cd148a66650e353b3b2af5c312fd4ef2b0cd9d444b18e
STEP 11: FROM alpine
STEP 12: COPY --from=uuid /src/data /uuid
--> e5a2fa361b7cfa0fb0d113c6762a2e9e415ac4b60a6b4326f21f8ab361ea1b07
STEP 13: FROM e5a2fa361b7cfa0fb0d113c6762a2e9e415ac4b60a6b4326f21f8ab361ea1b07
STEP 14: COPY --from=date /src/data /date
--> 9b365b2eb2a797b973ebfe46080af2ee196d0003f8eb3ddd19150845c68f603b
STEP 15: FROM 9b365b2eb2a797b973ebfe46080af2ee196d0003f8eb3ddd19150845c68f603b
STEP 16: CMD cat /uuid /date
--> 8574f2955110a8717896387859757d0151a103ec3d076d35838e3d08d0f31cf3
STEP 17: COMMIT test:1
podman run --rm test:$(cat VERSION)
2ad67301-5855-4eb3-9d91-7f8761e0fc7b
Thu 15 Nov 17:17:36 CET 2018
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make rand
mkdir -p uuid
uuidgen > uuid/data
mkdir -p date
date > date/data
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make run
echo $(( $(cat VERSION) + 1 )) > VERSION
podman build -t test:$(cat VERSION) .
STEP 1: FROM alpine AS uuid
STEP 2: COPY uuid /src
--> 4f9c4e86f0b6a80d561151e4df08b520dbd381af67a779e9b09debb52fd21ad3
STEP 3: FROM 4f9c4e86f0b6a80d561151e4df08b520dbd381af67a779e9b09debb52fd21ad3 AS uuid
STEP 4: RUN cat /src/data
7a3c06fe-732c-45e3-b891-25bf1843a3e6
--> 1f3c54c84abcc64da7ff8d2a827f38de78a3b9a3148f1344eb4aba49e0cf0456
STEP 5: COMMIT test:2
--> 6369bd47253d49051007d0c401ce1585405c0cadbd0a2dd2c6d9348812799d90
STEP 6: FROM alpine AS date
STEP 7: COPY date /src
--> 3664d97e64688daedff7505ace56911bcd157e973b00ebe0e518ddaeacff7856
STEP 8: FROM 3664d97e64688daedff7505ace56911bcd157e973b00ebe0e518ddaeacff7856 AS date
STEP 9: RUN cat /src/data
Thu 15 Nov 17:17:54 CET 2018
--> 8685073fd9b46d3dd58c94d5228b45ecd27d76c9244aa6d2b61dbd20bb78c9a6
STEP 10: COMMIT test:2
--> d2006a6f35a1f459a3c650b9ab53515b4d06adcb48dbe55a10cd088319e05a41
STEP 11: FROM alpine
STEP 12: COPY --from=uuid /src/data /uuid
--> Using cache e5a2fa361b7cfa0fb0d113c6762a2e9e415ac4b60a6b4326f21f8ab361ea1b07
STEP 13: FROM e5a2fa361b7cfa0fb0d113c6762a2e9e415ac4b60a6b4326f21f8ab361ea1b07
STEP 14: COPY --from=date /src/data /date
--> Using cache 9b365b2eb2a797b973ebfe46080af2ee196d0003f8eb3ddd19150845c68f603b
STEP 15: FROM 9b365b2eb2a797b973ebfe46080af2ee196d0003f8eb3ddd19150845c68f603b
STEP 16: CMD cat /uuid /date
--> Using cache 8574f2955110a8717896387859757d0151a103ec3d076d35838e3d08d0f31cf3
STEP 17: COMMIT test:2
podman run --rm test:$(cat VERSION)
2ad67301-5855-4eb3-9d91-7f8761e0fc7b
Thu 15 Nov 17:17:36 CET 2018
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ podman images
REPOSITORY                   TAG         IMAGE ID       CREATED          SIZE
<none>                       <none>      8685073fd9b4   15 seconds ago   4.68MB
<none>                       <none>      1f3c54c84abc   18 seconds ago   4.68MB
localhost/test               2           8574f2955110   29 seconds ago   4.68MB
localhost/test               1           8574f2955110   29 seconds ago   4.68MB
<none>                       <none>      d3814fa44bee   33 seconds ago   4.68MB
<none>                       <none>      42fa3dcc5492   36 seconds ago   4.68MB

```

No luck, it still tags the old image.

<details>
<summary>The same thing in Docker:</summary>

```
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ sed -i s/podman/docker/ makefile 
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ systemctl start docker
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make run
echo $(( $(cat VERSION) + 1 )) > VERSION
docker build -t test:$(cat VERSION) .
Sending build context to Docker daemon  7.168kB
Step 1/10 : FROM alpine AS uuid
 ---> 196d12cf6ab1
Step 2/10 : COPY uuid /src
 ---> cee5ea5c29c6
Step 3/10 : RUN cat /src/data
 ---> Running in 8fdd3d0af99b
7a3c06fe-732c-45e3-b891-25bf1843a3e6
Removing intermediate container 8fdd3d0af99b
 ---> 53662204cff5
Step 4/10 : FROM alpine AS date
 ---> 196d12cf6ab1
Step 5/10 : COPY date /src
 ---> 0bc2dcf36898
Step 6/10 : RUN cat /src/data
 ---> Running in 32cbb6f07cf6
Thu 15 Nov 17:17:54 CET 2018
Removing intermediate container 32cbb6f07cf6
 ---> f0f533321d35
Step 7/10 : FROM alpine
 ---> 196d12cf6ab1
Step 8/10 : COPY --from=uuid /src/data /uuid
 ---> 560a4f262def
Step 9/10 : COPY --from=date /src/data /date
 ---> 9ce9aad4c62d
Step 10/10 : CMD cat /uuid /date
 ---> Running in 2dc7ee544b2b
Removing intermediate container 2dc7ee544b2b
 ---> 0e1a9e9afd5d
Successfully built 0e1a9e9afd5d
Successfully tagged test:3
docker run --rm test:$(cat VERSION)
7a3c06fe-732c-45e3-b891-25bf1843a3e6
Thu 15 Nov 17:17:54 CET 2018
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make rand
mkdir -p uuid
uuidgen > uuid/data
mkdir -p date
date > date/data
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ make run
echo $(( $(cat VERSION) + 1 )) > VERSION
docker build -t test:$(cat VERSION) .
Sending build context to Docker daemon  7.168kB
Step 1/10 : FROM alpine AS uuid
 ---> 196d12cf6ab1
Step 2/10 : COPY uuid /src
 ---> 189d6d1b3102
Step 3/10 : RUN cat /src/data
 ---> Running in b23ed209bcd7
0d846ae8-9df6-4483-834f-78e2996f991d
Removing intermediate container b23ed209bcd7
 ---> c4ad75a67079
Step 4/10 : FROM alpine AS date
 ---> 196d12cf6ab1
Step 5/10 : COPY date /src
 ---> ca8b629e413f
Step 6/10 : RUN cat /src/data
 ---> Running in b4728df63771
Thu 15 Nov 17:22:48 CET 2018
Removing intermediate container b4728df63771
 ---> 6b834018eade
Step 7/10 : FROM alpine
 ---> 196d12cf6ab1
Step 8/10 : COPY --from=uuid /src/data /uuid
 ---> e05299fcbfdd
Step 9/10 : COPY --from=date /src/data /date
 ---> 47b81fb05570
Step 10/10 : CMD cat /uuid /date
 ---> Running in 1bfd411cd1e1
Removing intermediate container 1bfd411cd1e1
 ---> cb2f5190eabb
Successfully built cb2f5190eabb
Successfully tagged test:4
docker run --rm test:$(cat VERSION)
0d846ae8-9df6-4483-834f-78e2996f991d
Thu 15 Nov 17:22:48 CET 2018
⦁ ansemjo @thinkmett /tmp/tmp-gaslight-stopwatch-ZJa $ docker images
IMAGE ID            REPOSITORY                                   TAG                 SIZE
cb2f5190eabb        test                                         4                   4.41MB
6b834018eade        <none>                                       <none>              4.41MB
c4ad75a67079        <none>                                       <none>              4.41MB
0e1a9e9afd5d        test                                         3                   4.41MB
f0f533321d35        <none>                                       <none>              4.41MB
53662204cff5        <none>                                       <none>              4.41MB
```

This clearly builds and properly tags a new image.

</details>

**Comment by TomSweeneyRedHat** [comment]
@ansemjo thanks for the test and update!

**Comment by umohnani8** [comment]
@ansemjo thanks, looking into it!

**Comment by ansemjo** [comment]
You're welcome!

Adding a `--no-cache` to the build command sidesteps the issue as expected by not using any cache at all. But I think it is _at least_ unexpected behvaiour that the above multi-stage build does not tag the correct image with caching enabled.

**Comment by umohnani8** [comment]
Fixed in #1182

**Comment by ansemjo** [comment]
Yay! Eager to try this out tomorrow.
Thanks!

**Comment by ansemjo** [comment]
Is it enough to rebuild `buildah` from source or do I need to wait until it is included in a next `podman` release? Because currently I am still seeing this issue using `podman build` with `buildah` built from commit 2ac987a5.

**Comment by umohnani8** [comment]
@ansemjo if you build buildah from source again you should have the fix there. I am currently working on vendoring this fix into podman, so you won't see it in podman yet.
The libpod PR https://github.com/containers/libpod/pull/1838
