### ISSUE TITLE
memoryswap value not set correctly

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1213]
Now that we can read the cgroup values, our test that does so is occasionally flaking:

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21574/pull-ci-openshift-origin-master-e2e-gcp-crio/306

We set the values in buildah (note the value of MemorySwap):

```
 time="2018-12-03T11:53:10Z" level=debug msg="Resources: &buildah.CommonBuildOptions{AddHost:[]string(nil), CgroupParent:\"kubepods-podda5f0067_f6f1_11e8_afb3_42010a8e0005.slice\", CPUPeriod:0x0, CPUQuota:0, CPUShares:0x0, CPUSetCPUs:\"\", CPUSetMems:\"\", Memory:209715200, MemorySwap:209715200, LabelOpts:[]string(nil), SeccompProfilePath:\"\", ApparmorProfile:\"\", ShmSize:\"\", Ulimit:[]string(nil), Volumes:[]string(nil)}"
```

But when we read the value, memoryswap is wrong (though memory is correct):

```
 time="2018-12-03T11:53:23Z" level=debug msg="Running &exec.Cmd{Path:\"/bin/sh\", Args:[]string{\"/bin/sh\", \"-c\", \"/tmp/scripts/assemble\"}, Env:[]string{\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"BUILD_LOGLEVEL=6\", \"OPENSHIFT_BUILD_NAMESPACE=e2e-test-s2i-build-quota-lzbsk\", \"OPENSHIFT_BUILD_NAME=s2i-build-quota-1\"}, Dir:\"/\", Stdin:(*os.File)(0xc42000e010), Stdout:(*os.File)(0xc42000e018), Stderr:(*os.File)(0xc42000e020), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)} (PATH = \"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\")"
    MEMORY=209715200
    MEMORYSWAP=9223372036854771712
    QUOTA=6000
    SHARES=61
    PERIOD=100000
```

The script being executed within the Dockerfile is:
https://github.com/openshift/origin/blob/master/test/extended/testdata/builds/build-quota/.s2i/bin/assemble

specifically:
```

echo -n MEMORY= && cat /sys/fs/cgroup/memory/memory.limit_in_bytes
echo -n MEMORYSWAP= && cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
```

**Comment by rhatdan** [comment]
Is this occasional or every time?
@nalind @TomSweeneyRedHat PTAL

**Comment by bparees** [comment]
i believe it's intermittent, but i'm only seeing it in our "crio" job(where the cluster is running on crio) and not our other jobs.  But I don't see why this logic would care what the node runtime was, since we always use buildah within the pod and you can clearly see we read/passed the correct swap value to buildah, so it's not an issue of not getting it from the pod correctly.

**Comment by TomSweeneyRedHat** [comment]
The 9223372036854771712 value appears to be the default value found in  /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes.  Makes me wonder if we're by chance not actually setting that in the container?  Need to dig more.

**Comment by TomSweeneyRedHat** [comment]
@bparees I've looked, but haven't found it in the logs.  Are you running a command like:
`buildah bud -t tom -f ~/Dockerfile.alpine --memory=209715200 --memory-swap=209715200 .` under the covers?  I'm not able to get the memory or memory-swap values to "stick" when I do this via the `buildah bud` command, but when I do `ctr=$(buildah from --memory=209715200 --memory-swap=209715200 tom)` things seem to work OK.

**Comment by bparees** [comment]
> @bparees I've looked, but haven't found it in the logs. Are you running a command like:
buildah bud -t tom -f ~/Dockerfile.alpine --memory=209715200 --memory-swap=209715200 

we are using the buildah apis directly.  @nalind can point you to the integration points, but like i showed in the first log entry, we appear to be setting the options (and at least some of them stick):

time="2018-12-03T11:53:10Z" level=debug msg="Resources: &buildah.CommonBuildOptions{AddHost:[]string(nil), CgroupParent:\"kubepods-podda5f0067_f6f1_11e8_afb3_42010a8e0005.slice\", CPUPeriod:0x0, CPUQuota:0, CPUShares:0x0, CPUSetCPUs:\"\", CPUSetMems:\"\", Memory:209715200, MemorySwap:209715200, LabelOpts:[]string(nil), SeccompProfilePath:\"\", ApparmorProfile:\"\", ShmSize:\"\", Ulimit:[]string(nil), Volumes:[]string(nil)}"

Interestingly we do no appear to be setting cpu limits, but i guess those are being picked up from the container we are running buildah inside of?

**Comment by TomSweeneyRedHat** [comment]
Thanks @bparees I'll check with @nalind.

**Comment by TomSweeneyRedHat** [comment]
FWIW, I've checked in Docker  and Podman and the memoryswap/memory params passed in via the build commands seem to be ignored until a run command is issued.  The 'tom' images below is just alpine pulled down locally.  

```
# cat ~/Dockerfile.alpine
FROM alpine

# buildah bud -t tom -f ~/Dockerfile.alpine .
{snip happy build info}
Storing signatures
--> 50e3347d943e8be3b2ff6f171768b7bbbbd3c8c216dffffda4939f3f047151a6
```

Here's the Podman variant (replace podman below with docker for the same results):

```
#bui podman run --memory=209715200 --memory-swap=209715200 --detach --name=tomctr --net=host -v /var/lib/mycontainer:/var/lib/containers:Z  tom sh -c 'while true ;do wait; done'
76f7827215a4a9a6a44d740cd50a44cd72f981264deffc41b40f7bc245bd5f93
# podman exec -it tomctr /bin/sh 
/ #  cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
209715200
/ # cat /sys/fs/cgroup/memory/memory.limit_in_bytes
209715200
```

And if I do a `buildah from` then the container has the right memory setting when using Buildah.

```
# buildah from --memory=209715200 --memory-swap=209715200 -v /var/lib/mycontainer:/var/lib/containers:Z --name tomctr tom
tomctr
[root@localhost buildah]# buildah run tomctr /bin/sh 
/ # cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
209715200
/ # cat /sys/fs/cgroup/memory/memory.limit_in_bytes
209715200
```

So I'm not sure when or if the 'buildah from' command is being completed before the container is run in these tests?  Or perhaps the tests needs to check the values later in the process perhaps?  I think we may be looking at the difference here between `buildah run` (which is roughly equivalent to the RUN command in a Dockerfile) vs the docker/poodman run which is the full blown container run command that lets all kinds of options be set such as memory and memoryswap.

@nalind, thought on how we can proceed or adjust?

**Comment by TomSweeneyRedHat** [comment]
Note I'd a cut/paste error in the podman run command above, I've removed a rogue 'bui' from that command with my edit.

**Comment by TomSweeneyRedHat** [comment]
@bparees @nalind 
I ran through both Docker and Buildah/Podman again this morning.  The memoryswap and memory values are getting set inside the container only when a run command is executed as noted in previous comments for both Docker and Buildah/Podman.  The behavior in this space between Docker and Buildah/Podman is the same.

I noted: https://github.com/openshift/origin/commit/3194e2535b5d6be402d7dbfcb9cd40332b42170a#diff-d488e3020730d073b7ca207de92622a9 which put in a wait to let the "buildah log output stop before the container output starts".   Did this cure the problem?  Can we close this Issue?

@nalind, if not, thoughts on what to poke at next?

**Comment by bparees** [comment]
> I noted: [openshift/origin@3194e25#diff-d488e3020730d073b7ca207de92622a9](https://github.com/openshift/origin/commit/3194e2535b5d6be402d7dbfcb9cd40332b42170a#diff-d488e3020730d073b7ca207de92622a9) which put in a wait to let the "buildah log output stop before the container output starts". Did this cure the problem? Can we close this Issue?

No, that solved a different problem in which output was comingled.  

the memoryswap is still broken as far as i know and is disabled in the test here:
https://github.com/openshift/origin/blob/master/test/extended/builds/s2i_quota.go#L68

**Comment by TomSweeneyRedHat** [comment]
Hmm, the mystery deepens a bit more.  I tried to get a reproducer using:

```
# cat ~/Dockerfile.os_mem
FROM docker.io/busybox
LABEL "io.openshift.build.image"="docker.io/busybox" \
      "io.openshift.build.source-location"="/tmp/build/inputs"
ENV OPENSHIFT_BUILD_NAME="s2i-build-quota-1" \
    OPENSHIFT_BUILD_NAMESPACE="e2e-test-s2i-build-quota-lzbsk" \
    BUILD_LOGLEVEL="6"
USER root

# Copy assemble.sh to /tmp/scripts
COPY assemble.sh /tmp/scripts/assemble.sh

# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/scripts
USER 1001
RUN ls -RalF /tmp
RUN /tmp/scripts/assemble.sh

# cat assemble.sh
#!/bin/sh

# Seeing issues w/ buildah log output being intermingled with the container
# output, so adding a sleep in an attempt to let the buildah log output
# stop before the container output starts
sleep 10
echo -n MEMORY= && cat /sys/fs/cgroup/memory/memory.limit_in_bytes
echo -n MEMORYSWAP= && cat /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes

if [ -e /sys/fs/cgroup/cpuacct,cpu ]; then
	quota=$(</sys/fs/cgroup/cpuacct,cpu/cpu.cfs_quota_us)
	echo -n QUOTA= && cat /sys/fs/cgroup/cpuacct,cpu/cpu.cfs_quota_us
	echo -n SHARES= && cat /sys/fs/cgroup/cpuacct,cpu/cpu.shares
	echo -n PERIOD= && cat /sys/fs/cgroup/cpuacct,cpu/cpu.cfs_period_us
else
	quota=$(</sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us)
	echo -n QUOTA= && cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
	echo -n SHARES= && cat /sys/fs/cgroup/cpu,cpuacct/cpu.shares
	echo -n PERIOD= && cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us
fi

if [ "${quota}" == "-1" ]; then
	cat /proc/self/cgroup
	cat /proc/self/mountinfo
	findmnt
fi
```

and then ran:

```
# buildah bud -t tom --memory=209715200 --memory-swap=209715200 -f ~/Dockerfile.os_mem .
STEP 1: FROM docker.io/busybox
STEP 2: LABEL "io.openshift.build.image"="docker.io/busybox"       "io.openshift.build.source-location"="/tmp/build/inputs"
{removed happy build lines}
STEP 9: RUN /tmp/scripts/assemble.sh
MEMORY=209715200
MEMORYSWAP=209715200
QUOTA=-1
SHARES=1024
PERIOD=100000
STEP 10: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]localhost/tom:latest
{Removed more happy build output}
```

Was really hoping and suspecting that the MEMORYSWAP variable  would not be the right size as it is.  The only other thing I can think of off the top of my head is how that value is potentially handled in BuildOptions...

**Comment by rhatdan** [comment]
@bparees @TomSweeneyRedHat Any movement on this?

**Comment by bparees** [comment]
still broken:
```
    MEMORY=209715200
    MEMORYSWAP=9223372036854771712
    QUOTA=6000
    SHARES=61
    PERIOD=100000
```

**Comment by rhatdan** [comment]
Ok @TomSweeneyRedHat we need to raise the priority on this one.

**Comment by TomSweeneyRedHat** [comment]
OK, i' d looked for a reproducer in Buildah side couldn't ever reproduce it there.  The memoryswap value was being set appropriately in every test and stage that I could find.  My only thought is the OCP tests are somehow checking it too early or perhaps are following another path than my tests do?

I'm out of ideas on how to diagnose/track this down further.  @nalind any thoughts?

**Comment by bparees** [comment]
the ocp tests aren't "checking it", we're just printing it directly via a RUN directive in the dockerfile.  They may be following a different path however, since we are using the buildah apis to do the build, not invoking "buildah bud" from the cli.

**Comment by rhatdan** [comment]
Perhaps it is in the OpenShift code, not setting the field correctly?  Or it could be fixed in a new version of Buildah (Although I doubt it).

**Comment by TomSweeneyRedHat** [comment]
Yeah I don't think it's fixed in latest buildah, there's no changes there that I'm aware of in regards to memory or memoryswap.  From what I can see of the OCP calls, they look reasonable.  It's driving me a bit batty.

**Comment by bparees** [comment]
> Perhaps it is in the OpenShift code, not setting the field correctly? 

near as i can tell we're setting it correctly:

```
time="2018-12-03T11:53:10Z" level=debug msg="Resources: &buildah.CommonBuildOptions{AddHost:[]string(nil), CgroupParent:"kubepods-podda5f0067_f6f1_11e8_afb3_42010a8e0005.slice", CPUPeriod:0x0, CPUQuota:0, CPUShares:0x0, CPUSetCPUs:"", CPUSetMems:"", Memory:209715200, MemorySwap:209715200, LabelOpts:[]string(nil), SeccompProfilePath:"", ApparmorProfile:"", ShmSize:"", Ulimit:[]string(nil), Volumes:[]string(nil)}"
```

**Comment by TomSweeneyRedHat** [comment]
@bparees can you tell me if this is the code that you're running to do the build of the container?

https://github.com/openshift/builder/blob/918f4590f10bc644bd0e2d8a481469410bb825d6/pkg/build/builder/daemonless.go#L155

If not, could you give me a GitHub pointer to the code in OpenShift  that's putting the value for MemorySwap into CommonBuildOptions and then calling buildah or imagebuilder to make the container image?

Thanks!

**Comment by TomSweeneyRedHat** [comment]
OK one other OpenShift code newb question.  The other spot that I see MemorySwap being toggled in the OpenShift code is in `GetCGroupLimits()`: 
https://github.com/openshift/builder/blob/10af739de1d3d8a7e2e4ab1b0c3ba9008e012219/pkg/build/builder/util_linux.go#L43

Which looks likes it gets called at times via hooks after the container is up and running.  Is it possible that a hook is mucking with the MemorySwap value post creation but before the test checks the value?  I don't see the Memory field getting changed in that function.

**Comment by bparees** [comment]
> @bparees can you tell me if this is the code that you're running to do the build of the container?

yes that should be it.

> OK one other OpenShift code newb question. The other spot that I see MemorySwap being toggled in the OpenShift code is in GetCGroupLimits():

it's not being toggled there, that's where we fetch the value from the pod we're running inside, so we can set it in the code you found when we invoke buildah.

ultimate this log statement:
```
time="2018-12-03T11:53:10Z" level=debug msg="Resources: &buildah.CommonBuildOptions{AddHost:[]string(nil), CgroupParent:"kubepods-podda5f0067_f6f1_11e8_afb3_42010a8e0005.slice", CPUPeriod:0x0, CPUQuota:0, CPUShares:0x0, CPUSetCPUs:"", CPUSetMems:"", Memory:209715200, MemorySwap:209715200, LabelOpts:[]string(nil), SeccompProfilePath:"", ApparmorProfile:"", ShmSize:"", Ulimit:[]string(nil), Volumes:[]string(nil)}"
```

is coming after we've invoked GetCGroupLimits() to determine what the pod's memoryswap limit is, and set it in CommonBuildOptions to pass it to buildah.

>  Is it possible that a hook is mucking with the MemorySwap value post creation but before the test checks the value?

i'm not sure what sort of hook could do that?  Agai the log statement above is from buildah itself as i understand it, so at that point buildah has the value, it begins processing/building the Dockerfile.  Part of building that dockerfile entails executing a "RUN assemble.sh" directive.  The assemble.sh script prints out what it sees the cgroup memoryswap limit as being.  Since that assemble.sh is presumably executing inside the container buildah created to execute the dockerfile directives, the conclusion I reached is that buildah has not set the memoryswap limit on the container properly, or however it executes the RUN directives.

**Comment by bparees** [comment]
just to make it even clearer, here's the full verbose output from buildah when it is processing the RUN directive (this is from the original build log in my initial report, so buildah output may have changed since this, but the behavior doesn't seem to have).

You can see that buildah is executing the "RUN assemble" step of the dockerfile, it reports that it is running it with options that include `"memory\":{\"limit\":209715200,\"swap\":209715200}}` and then you can see that when the assemble script executes and prints the cgroup limits, the memory swap value is not 209715200:


```
STEP 9: RUN /tmp/scripts/assemble
time="2018-12-03T11:53:10Z" level=debug msg="RUN imagebuilder.Run{Shell:true, Args:[]string{\"/tmp/scripts/assemble\"}}, docker.Config{Hostname:\"af32d21812ce\", Domainname:\"\", User:\"1001\", Memory:0, MemorySwap:0, MemoryReservation:0, KernelMemory:0, CPUShares:0, CPUSet:\"\", PortSpecs:[]string(nil), ExposedPorts:map[docker.Port]struct {}{}, PublishService:\"\", StopSignal:\"\", StopTimeout:0, Env:[]string{\"BUILD_LOGLEVEL=6\", \"OPENSHIFT_BUILD_NAMESPACE=e2e-test-s2i-build-quota-lzbsk\", \"OPENSHIFT_BUILD_NAME=s2i-build-quota-1\", \"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"\", \"\", \"\", \"OPENSHIFT_BUILD_NAME=s2i-build-quota-1\", \"OPENSHIFT_BUILD_NAMESPACE=e2e-test-s2i-build-quota-lzbsk\", \"BUILD_LOGLEVEL=6\"}, Cmd:[]string{\"sh\"}, Shell:[]string{}, Healthcheck:(*docker.HealthConfig)(nil), DNS:[]string(nil), Image:\"\", Volumes:map[string]struct {}{}, VolumeDriver:\"\", WorkingDir:\"\", MacAddress:\"\", Entrypoint:[]string{}, SecurityOpts:[]string(nil), OnBuild:[]string{}, Mounts:[]docker.Mount(nil), Labels:map[string]string{\"io.openshift.build.image\":\"docker.io/busybox\", \"io.openshift.build.source-location\":\"/tmp/build/inputs\"}, AttachStdin:false, AttachStdout:false, AttachStderr:false, ArgsEscaped:false, Tty:false, OpenStdin:false, StdinOnce:false, NetworkDisabled:false, VolumesFrom:\"\"}"
time="2018-12-03T11:53:10Z" level=debug msg="using \"/tmp/buildah455878884\" to hold bundle data"
time="2018-12-03T11:53:10Z" level=debug msg="Resources: &buildah.CommonBuildOptions{AddHost:[]string(nil), CgroupParent:\"kubepods-podda5f0067_f6f1_11e8_afb3_42010a8e0005.slice\", CPUPeriod:0x0, CPUQuota:0, CPUShares:0x0, CPUSetCPUs:\"\", CPUSetMems:\"\", Memory:209715200, MemorySwap:209715200, LabelOpts:[]string(nil), SeccompProfilePath:\"\", ApparmorProfile:\"\", ShmSize:\"\", Ulimit:[]string(nil), Volumes:[]string(nil)}"
time="2018-12-03T11:53:10Z" level=debug msg="stdio is not a terminal, defaulting to not using a terminal"
time="2018-12-03T11:53:14Z" level=debug msg="ensuring working directory \"/var/lib/containers/storage/overlay/6ca2a3f8650afccb82891761e87d4f323d770d8b3518b715bcaa91657bd30d87/merged\" exists"
time="2018-12-03T11:53:14Z" level=debug msg="CopyFileWithTar(/etc/hosts, /tmp/buildah455878884/hosts)"
time="2018-12-03T11:53:17Z" level=debug msg="CopyFileWithTar(/etc/resolv.conf, /tmp/buildah455878884/resolv.conf)"
time="2018-12-03T11:53:19Z" level=debug msg="/etc/system-fips does not exist on host, not mounting FIPS mode secret"
time="2018-12-03T11:53:19Z" level=debug msg="setting up mounted volume at \"/run/secrets\""
time="2018-12-03T11:53:19Z" level=debug msg="config = {\"ociVersion\":\"1.0.1-dev\",\"process\":{\"user\":{\"uid\":1001,\"gid\":0},\"args\":[\"/bin/sh\",\"-c\",\"/tmp/scripts/assemble\"],\"env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"BUILD_LOGLEVEL=6\",\"OPENSHIFT_BUILD_NAMESPACE=e2e-test-s2i-build-quota-lzbsk\",\"OPENSHIFT_BUILD_NAME=s2i-build-quota-1\"],\"cwd\":\"/\",\"capabilities\":{\"bounding\":[\"CAP_AUDIT_WRITE\",\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_MKNOD\",\"CAP_NET_BIND_SERVICE\",\"CAP_SETFCAP\",\"CAP_SETGID\",\"CAP_SETPCAP\",\"CAP_SETUID\",\"CAP_SYS_CHROOT\"]},\"rlimits\":[{\"type\":\"RLIMIT_NOFILE\",\"hard\":1024,\"soft\":1024}]},\"root\":{\"path\":\"/var/lib/containers/storage/overlay/6ca2a3f8650afccb82891761e87d4f323d770d8b3518b715bcaa91657bd30d87/merged\"},\"hostname\":\"af32d21812ce\",\"mounts\":[{\"destination\":\"/run/secrets\",\"type\":\"bind\",\"source\":\"/run/secrets\",\"options\":[\"ro\",\"nodev\",\"noexec\",\"nosuid\",\"rbind\",\"private\"]},{\"destination\":\"/etc/hosts\",\"type\":\"bind\",\"source\":\"/tmp/buildah455878884/hosts\",\"options\":[\"rbind\",\"nobuildahbind\"]},{\"destination\":\"/etc/resolv.conf\",\"type\":\"bind\",\"source\":\"/tmp/buildah455878884/resolv.conf\",\"options\":[\"rbind\",\"nobuildahbind\"]},{\"destination\":\"/proc\",\"type\":\"proc\",\"source\":\"proc\",\"options\":[\"nosuid\",\"noexec\",\"nodev\"]},{\"destination\":\"/dev\",\"type\":\"tmpfs\",\"source\":\"tmpfs\",\"options\":[\"nosuid\",\"strictatime\",\"mode=755\",\"size=65536k\"]},{\"destination\":\"/dev/pts\",\"type\":\"devpts\",\"source\":\"devpts\",\"options\":[\"nosuid\",\"noexec\",\"newinstance\",\"ptmxmode=0666\",\"mode=0620\",\"gid=5\"]},{\"destination\":\"/dev/shm\",\"type\":\"tmpfs\",\"source\":\"shm\",\"options\":[\"nosuid\",\"noexec\",\"nodev\",\"mode=1777\",\"size=\"]},{\"destination\":\"/dev/mqueue\",\"type\":\"mqueue\",\"source\":\"mqueue\",\"options\":[\"nosuid\",\"noexec\",\"nodev\"]},{\"destination\":\"/sys\",\"type\":\"sysfs\",\"source\":\"sysfs\",\"options\":[\"nosuid\",\"noexec\",\"nodev\",\"ro\"]},{\"destination\":\"/sys/fs/cgroup\",\"type\":\"cgroup\",\"source\":\"cgroup\",\"options\":[\"nobuildahbind\",\"nosuid\",\"noexec\",\"nodev\",\"relatime\",\"ro\"]}],\"linux\":{\"resources\":{\"devices\":[{\"allow\":false,\"access\":\"rwm\"}],\"memory\":{\"limit\":209715200,\"swap\":209715200}},\"cgroupsPath\":\"kubepods-podda5f0067_f6f1_11e8_afb3_42010a8e0005.slice\",\"namespaces\":[{\"type\":\"pid\"},{\"type\":\"ipc\"},{\"type\":\"uts\"},{\"type\":\"mount\"}],\"maskedPaths\":[\"/proc/acpi\",\"/proc/kcore\",\"/proc/keys\",\"/proc/latency_stats\",\"/proc/timer_list\",\"/proc/timer_stats\",\"/proc/sched_debug\",\"/proc/scsi\",\"/sys/firmware\"],\"readonlyPaths\":[\"/proc/asound\",\"/proc/bus\",\"/proc/fs\",\"/proc/irq\",\"/proc/sys\",\"/proc/sysrq-trigger\"]}}"
time="2018-12-03T11:53:19Z" level=debug msg="Running &exec.Cmd{Path:\"/proc/self/exe\", Args:[]string{\"buildah-chroot-runtime\"}, Env:[]string{\"LOGLEVEL=5\", \"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"TERM=xterm\", \"HOSTNAME=s2i-build-quota-1-build\", \"ALLOWED_UIDS=1-\", \"BUILD_REGISTRIES_CONF_PATH=/var/run/configs/openshift.io/build-system/registries.conf\", \"BUILD_STORAGE_CONF_PATH=/var/run/configs/openshift.io/build-system/storage.conf\", \"BUILD_STORAGE_DRIVER=overlay\", \"BUILD_LOGLEVEL=6\", \"DROP_CAPS=KILL,MKNOD,SETGID,SETUID\", \"PULL_DOCKERCFG_PATH=/var/run/secrets/openshift.io/pull\", \"BUILD_REGISTRIES_DIR_PATH=/var/run/configs/openshift.io/build-system/registries.d\", \"BUILD_SIGNATURE_POLICY_PATH=/var/run/configs/openshift.io/build-system/signature-policy.json\", \"BUILD_ISOLATION=chroot\", \"BUILD={\\\"kind\\\":\\\"Build\\\",\\\"apiVersion\\\":\\\"build.openshift.io/v1\\\",\\\"metadata\\\":{\\\"name\\\":\\\"s2i-build-quota-1\\\",\\\"namespace\\\":\\\"e2e-test-s2i-build-quota-lzbsk\\\",\\\"selfLink\\\":\\\"/apis/build.openshift.io/v1/namespaces/e2e-test-s2i-build-quota-lzbsk/builds/s2i-build-quota-1\\\",\\\"uid\\\":\\\"da33d391-f6f1-11e8-afb3-42010a8e0005\\\",\\\"resourceVersion\\\":\\\"33871\\\",\\\"creationTimestamp\\\":\\\"2018-12-03T11:52:04Z\\\",\\\"labels\\\":{\\\"buildconfig\\\":\\\"s2i-build-quota\\\",\\\"name\\\":\\\"s2i-build-quota\\\",\\\"openshift.io/build-config.name\\\":\\\"s2i-build-quota\\\",\\\"openshift.io/build.start-policy\\\":\\\"Serial\\\"},\\\"annotations\\\":{\\\"openshift.io/build-config.name\\\":\\\"s2i-build-quota\\\",\\\"openshift.io/build.number\\\":\\\"1\\\"},\\\"ownerReferences\\\":[{\\\"apiVersion\\\":\\\"build.openshift.io/v1\\\",\\\"kind\\\":\\\"BuildConfig\\\",\\\"name\\\":\\\"s2i-build-quota\\\",\\\"uid\\\":\\\"d8f4bc76-f6f1-11e8-afb3-42010a8e0005\\\",\\\"controller\\\":true}]},\\\"spec\\\":{\\\"serviceAccount\\\":\\\"builder\\\",\\\"source\\\":{\\\"type\\\":\\\"Binary\\\",\\\"binary\\\":{}},\\\"strategy\\\":{\\\"type\\\":\\\"Source\\\",\\\"sourceStrategy\\\":{\\\"from\\\":{\\\"kind\\\":\\\"DockerImage\\\",\\\"name\\\":\\\"docker.io/busybox\\\"},\\\"pullSecret\\\":{\\\"name\\\":\\\"builder-dockercfg-vf7kp\\\"},\\\"env\\\":[{\\\"name\\\":\\\"BUILD_LOGLEVEL\\\",\\\"value\\\":\\\"6\\\"}]}},\\\"output\\\":{},\\\"resources\\\":{\\\"limits\\\":{\\\"cpu\\\":\\\"60m\\\",\\\"memory\\\":\\\"200Mi\\\"}},\\\"postCommit\\\":{},\\\"nodeSelector\\\":null,\\\"triggeredBy\\\":null},\\\"status\\\":{\\\"phase\\\":\\\"New\\\",\\\"config\\\":{\\\"kind\\\":\\\"BuildConfig\\\",\\\"namespace\\\":\\\"e2e-test-s2i-build-quota-lzbsk\\\",\\\"name\\\":\\\"s2i-build-quota\\\"},\\\"output\\\":{}}}\\n\", \"KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1\", \"KUBERNETES_SERVICE_PORT_HTTPS=443\", \"KUBERNETES_SERVICE_PORT_DNS=53\", \"KUBERNETES_PORT_443_TCP_PORT=443\", \"KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1\", \"KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53\", \"KUBERNETES_SERVICE_PORT=443\", \"KUBERNETES_PORT=tcp://172.30.0.1:443\", \"KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53\", \"KUBERNETES_PORT_53_UDP_PROTO=udp\", \"KUBERNETES_PORT_53_UDP_PORT=53\", \"KUBERNETES_PORT_53_TCP_PROTO=tcp\", \"KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1\", \"KUBERNETES_SERVICE_PORT_DNS_TCP=53\", \"KUBERNETES_PORT_443_TCP_PROTO=tcp\", \"KUBERNETES_PORT_53_TCP_PORT=53\", \"KUBERNETES_SERVICE_HOST=172.30.0.1\", \"KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443\", \"OPENSHIFT_BUILD_NAME=docker-builder\", \"OPENSHIFT_BUILD_NAMESPACE=ci-op-xnjcbi6k\", \"HOME=/root\"}, Dir:\"/\", Stdin:(*os.File)(0xc420100068), Stdout:(*os.File)(0xc42000e018), Stderr:(*os.File)(0xc42000e018), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(0xc4205701e0), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)} in &unshare.Cmd{Cmd:(*exec.Cmd)(0xc4203b1760), UnshareFlags:0, UseNewuidmap:false, UidMappings:[]specs.LinuxIDMapping(nil), UseNewgidmap:false, GidMappings:[]specs.LinuxIDMapping(nil), GidMappingsEnableSetgroups:false, Setsid:false, Setpgrp:false, Ctty:(*os.File)(nil), OOMScoreAdj:(*int)(nil), Hook:(func(int) error)(nil)}"
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/var/lib/containers/storage/overlay/6ca2a3f8650afccb82891761e87d4f323d770d8b3518b715bcaa91657bd30d87/merged\" to \"/tmp/buildah455878884/mnt/rootfs\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/run/secrets\" to \"/tmp/buildah455878884/mnt/buildah-bind-target-0\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/dev\" to \"/tmp/buildah455878884/mnt/rootfs/dev\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/proc\" to \"/tmp/buildah455878884/mnt/rootfs/proc\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/sys\" to \"/tmp/buildah455878884/mnt/rootfs/sys\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/tmp/buildah455878884/mnt/buildah-bind-target-0\" to \"/tmp/buildah455878884/mnt/rootfs/run/secrets\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/tmp/buildah455878884/hosts\" to \"/tmp/buildah455878884/mnt/rootfs/etc/hosts\""
time="2018-12-03T11:53:21Z" level=debug msg="bind mounted \"/tmp/buildah455878884/resolv.conf\" to \"/tmp/buildah455878884/mnt/rootfs/etc/resolv.conf\""
time="2018-12-03T11:53:21Z" level=debug msg="already bind mounted \"/proc\" on \"/tmp/buildah455878884/mnt/rootfs/proc\""
time="2018-12-03T11:53:21Z" level=debug msg="already bind mounted \"/dev\" on \"/tmp/buildah455878884/mnt/rootfs/dev\""
time="2018-12-03T11:53:21Z" level=debug msg="already bind mounted \"/sys\" on \"/tmp/buildah455878884/mnt/rootfs/sys\""
time="2018-12-03T11:53:21Z" level=debug msg="unable to create PID namespace, sorry about that"
time="2018-12-03T11:53:21Z" level=debug msg="unable to create IPC namespace, sorry about that"
time="2018-12-03T11:53:21Z" level=debug msg="user namespace not requested, but creating a new one anyway"
time="2018-12-03T11:53:21Z" level=debug msg="Running &exec.Cmd{Path:\"/proc/self/exe\", Args:[]string{\"buildah-chroot-exec\", \"/bin/sh\", \"-c\", \"/tmp/scripts/assemble\"}, Env:[]string{\"LOGLEVEL=5\", \"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"TERM=xterm\", \"HOSTNAME=s2i-build-quota-1-build\", \"ALLOWED_UIDS=1-\", \"BUILD_REGISTRIES_CONF_PATH=/var/run/configs/openshift.io/build-system/registries.conf\", \"BUILD_STORAGE_CONF_PATH=/var/run/configs/openshift.io/build-system/storage.conf\", \"BUILD_STORAGE_DRIVER=overlay\", \"BUILD_LOGLEVEL=6\", \"DROP_CAPS=KILL,MKNOD,SETGID,SETUID\", \"PULL_DOCKERCFG_PATH=/var/run/secrets/openshift.io/pull\", \"BUILD_REGISTRIES_DIR_PATH=/var/run/configs/openshift.io/build-system/registries.d\", \"BUILD_SIGNATURE_POLICY_PATH=/var/run/configs/openshift.io/build-system/signature-policy.json\", \"BUILD_ISOLATION=chroot\", \"BUILD={\\\"kind\\\":\\\"Build\\\",\\\"apiVersion\\\":\\\"build.openshift.io/v1\\\",\\\"metadata\\\":{\\\"name\\\":\\\"s2i-build-quota-1\\\",\\\"namespace\\\":\\\"e2e-test-s2i-build-quota-lzbsk\\\",\\\"selfLink\\\":\\\"/apis/build.openshift.io/v1/namespaces/e2e-test-s2i-build-quota-lzbsk/builds/s2i-build-quota-1\\\",\\\"uid\\\":\\\"da33d391-f6f1-11e8-afb3-42010a8e0005\\\",\\\"resourceVersion\\\":\\\"33871\\\",\\\"creationTimestamp\\\":\\\"2018-12-03T11:52:04Z\\\",\\\"labels\\\":{\\\"buildconfig\\\":\\\"s2i-build-quota\\\",\\\"name\\\":\\\"s2i-build-quota\\\",\\\"openshift.io/build-config.name\\\":\\\"s2i-build-quota\\\",\\\"openshift.io/build.start-policy\\\":\\\"Serial\\\"},\\\"annotations\\\":{\\\"openshift.io/build-config.name\\\":\\\"s2i-build-quota\\\",\\\"openshift.io/build.number\\\":\\\"1\\\"},\\\"ownerReferences\\\":[{\\\"apiVersion\\\":\\\"build.openshift.io/v1\\\",\\\"kind\\\":\\\"BuildConfig\\\",\\\"name\\\":\\\"s2i-build-quota\\\",\\\"uid\\\":\\\"d8f4bc76-f6f1-11e8-afb3-42010a8e0005\\\",\\\"controller\\\":true}]},\\\"spec\\\":{\\\"serviceAccount\\\":\\\"builder\\\",\\\"source\\\":{\\\"type\\\":\\\"Binary\\\",\\\"binary\\\":{}},\\\"strategy\\\":{\\\"type\\\":\\\"Source\\\",\\\"sourceStrategy\\\":{\\\"from\\\":{\\\"kind\\\":\\\"DockerImage\\\",\\\"name\\\":\\\"docker.io/busybox\\\"},\\\"pullSecret\\\":{\\\"name\\\":\\\"builder-dockercfg-vf7kp\\\"},\\\"env\\\":[{\\\"name\\\":\\\"BUILD_LOGLEVEL\\\",\\\"value\\\":\\\"6\\\"}]}},\\\"output\\\":{},\\\"resources\\\":{\\\"limits\\\":{\\\"cpu\\\":\\\"60m\\\",\\\"memory\\\":\\\"200Mi\\\"}},\\\"postCommit\\\":{},\\\"nodeSelector\\\":null,\\\"triggeredBy\\\":null},\\\"status\\\":{\\\"phase\\\":\\\"New\\\",\\\"config\\\":{\\\"kind\\\":\\\"BuildConfig\\\",\\\"namespace\\\":\\\"e2e-test-s2i-build-quota-lzbsk\\\",\\\"name\\\":\\\"s2i-build-quota\\\"},\\\"output\\\":{}}}\\n\", \"KUBERNETES_PORT_53_UDP_ADDR=172.30.0.1\", \"KUBERNETES_SERVICE_PORT_HTTPS=443\", \"KUBERNETES_SERVICE_PORT_DNS=53\", \"KUBERNETES_PORT_443_TCP_PORT=443\", \"KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1\", \"KUBERNETES_PORT_53_TCP=tcp://172.30.0.1:53\", \"KUBERNETES_SERVICE_PORT=443\", \"KUBERNETES_PORT=tcp://172.30.0.1:443\", \"KUBERNETES_PORT_53_UDP=udp://172.30.0.1:53\", \"KUBERNETES_PORT_53_UDP_PROTO=udp\", \"KUBERNETES_PORT_53_UDP_PORT=53\", \"KUBERNETES_PORT_53_TCP_PROTO=tcp\", \"KUBERNETES_PORT_53_TCP_ADDR=172.30.0.1\", \"KUBERNETES_SERVICE_PORT_DNS_TCP=53\", \"KUBERNETES_PORT_443_TCP_PROTO=tcp\", \"KUBERNETES_PORT_53_TCP_PORT=53\", \"KUBERNETES_SERVICE_HOST=172.30.0.1\", \"KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443\", \"OPENSHIFT_BUILD_NAME=docker-builder\", \"OPENSHIFT_BUILD_NAMESPACE=ci-op-xnjcbi6k\", \"HOME=/root\", \"_LIBPOD_USERNS_CONFIGURED=done\", \"_LIBPOD_ROOTLESS_UID=0\"}, Dir:\"/\", Stdin:(*os.File)(0xc4200bc438), Stdout:(*os.File)(0xc4200bc450), Stderr:(*os.File)(0xc4200bc460), ExtraFiles:[]*os.File{(*os.File)(0xc42000e030)}, SysProcAttr:(*syscall.SysProcAttr)(0xc420780000), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)} in &unshare.Cmd{Cmd:(*exec.Cmd)(0xc4203cd4a0), UnshareFlags:67239936, UseNewuidmap:false, UidMappings:[]specs.LinuxIDMapping(nil), UseNewgidmap:false, GidMappings:[]specs.LinuxIDMapping(nil), GidMappingsEnableSetgroups:false, Setsid:false, Setpgrp:false, Ctty:(*os.File)(nil), OOMScoreAdj:(*int)(nil), Hook:(func(int) error)(0x12dc360)}"
time="2018-12-03T11:53:23Z" level=debug msg="chrooted into \"/tmp/buildah455878884/mnt/rootfs\""
time="2018-12-03T11:53:23Z" level=debug msg="setting apparmor profile"
time="2018-12-03T11:53:23Z" level=debug msg="setting resource limits"
time="2018-12-03T11:53:23Z" level=debug msg="changed working directory to \"/\""
time="2018-12-03T11:53:23Z" level=debug msg="clearing supplemental groups"
time="2018-12-03T11:53:23Z" level=debug msg="setting gid"
time="2018-12-03T11:53:23Z" level=debug msg="setting capabilities"
time="2018-12-03T11:53:23Z" level=debug msg="setting uid"
time="2018-12-03T11:53:23Z" level=debug msg="Running &exec.Cmd{Path:\"/bin/sh\", Args:[]string{\"/bin/sh\", \"-c\", \"/tmp/scripts/assemble\"}, Env:[]string{\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"BUILD_LOGLEVEL=6\", \"OPENSHIFT_BUILD_NAMESPACE=e2e-test-s2i-build-quota-lzbsk\", \"OPENSHIFT_BUILD_NAME=s2i-build-quota-1\"}, Dir:\"/\", Stdin:(*os.File)(0xc42000e010), Stdout:(*os.File)(0xc42000e018), Stderr:(*os.File)(0xc42000e020), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)} (PATH = \"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\")"
MEMORY=209715200
MEMORYSWAP=9223372036854771712
QUOTA=6000
SHARES=61
PERIOD=100000
time="2018-12-03T11:53:24Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah455878884/mnt/rootfs\": error checking if \"/tmp/buildah455878884/mnt/rootfs/sys/fs/cgroup/pids\" is mounted: no such file or directory"
```

note that the above output also reports this (before reporting the buildoptions):

```
docker.Config{Hostname:\"af32d21812ce\", Domainname:\"\", User:\"1001\", Memory:0, MemorySwap:0, MemoryReservation:0, KernelMemory:0, CPUShares:0, CPUSet:\"\", PortSpecs:[]string(nil), ExposedPorts:map[docker.Port]struct {}{}
```

in which the swap value is reported as zero.  This looks like it's the config information for the base image(?) so i wouldn't think it matters, but perhaps it's somehow relevant to why buildah is using the wrong value?

**Comment by bparees** [comment]
you can find the full log file here:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/21574/pull-ci-openshift-origin-master-e2e-gcp-crio/306/build-log.txt

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Ping

**Comment by rhatdan** [comment]
@TomSweeneyRedHat This was never fixed correct, or you could never reproduce?

**Comment by TomSweeneyRedHat** [comment]
Yes too both.  It's still an issue and I've not been able to reproduce.  @nalind and I had talked about possible scenario's to try a month or two ago, but I then go hijacked with other fires.

**Comment by nalind** [comment]
The OpenShift builder uses buildah's chroot isolation, which doesn't implement setting control group settings.

Because the builder is run in a container, and the we can count on that container having its `memory.limit_in_bytes` limit set on its behalf by the runtime (CRI-O), so we don't have to do anything for that limit, and a couple of others.

Kubernetes doesn't provide a control for the `memory.memsw.limit_in_bytes` limit, though, so CRI-O can't handle swap limits for us, which means we'll need to add logic to do it ourselves.  Hopefully we can use libcontainer for that, because sorting out v1 vs. v2 names for settings, along with whether or not we're running inside of a container, which affects the v1 paths, is not that appealing.

**Comment by rhatdan** [comment]
@nalind @bparees @TomSweeneyRedHat @giuseppe Is this still an issue?

**Comment by bparees** [comment]
the test that was flaking due to this is still disabled pending the resolution to this issue, so i don't know if it's still happening or not.

**Comment by nalind** [comment]
I think OpenShift should be alright with a version of CRI-O that incorporates https://github.com/cri-o/cri-o/pull/3564, but we haven't made changes to buildah to do the work for other cases.

**Comment by TomSweeneyRedHat** [comment]
I think it actually might be working OK now in Buildah too.  I need to retest/check as I was poking at something else and it seemed like things were OK here now, but need to double check.  Then again, it was a late night test, so who knows?

**Comment by rhatdan** [comment]
I think this is fixed, reopen if I am mistaken.

**Comment by bparees** [comment]
this test is still not re-enabled:
https://github.com/openshift/origin/blob/master/test/extended/builds/s2i_quota.go#L60

@adambkaplan do you want to re-enable it in a PR and see if it's working now?  As i recall it was a flake you'll need to test the PR a few times to have confidence.
