### ISSUE TITLE
COPY to absolute paths is relative to WORKDIR

### ISSUE THREAD

**Issue by chpio** [containers/buildah#1628]
**Description**

`COPY` resolves absolute paths relative to `WORKDIR`.

> The `<dest>` is an absolute path, or a path relative to `WORKDIR`, into which the source will be copied inside the destination container.
> 
> ```dockerfile
> COPY test relativeDir/   # adds "test" to `WORKDIR`/relativeDir/
> COPY test /absoluteDir/  # adds "test" to /absoluteDir/
> ```
>
> -- https://docs.docker.com/engine/reference/builder/#copy

**Describe the results you received:**

```dockerfile
WORKDIR /var
COPY fs /
```

will copy files in the *fs*-dir into */var*.

**Describe the results you expected:**

Absolute destinations in `COPY` should be handled as *absolute* paths.

**Output of `podman version` if reporting a `podman build` issue:**

```
$ podman version
Version:            1.3.2-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux thomas-laptop 5.1.5-050105-generic #201905251333 SMP Sat May 25 17:36:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by QiWang19** [comment]
Buildah v1.8.3 has been vendored in podman. This issue has been solved in buildah and podman.

**Comment by chpio** [comment]
```
$ podman version
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

https://github.com/containers/libpod/blob/v1.4.0/vendor.conf#L96

this is still broken

**Comment by chpio** [comment]
https://github.com/chpio/podman-copy

**Comment by chpio** [comment]
ok, sorry, seemed to be a cache problem

**Comment by TomSweeneyRedHat** [comment]
@chpio I think it's all set now, but I'm not 100% sure based on your comments.  If you'd like us to reopen this, please add a reply here or feel free to create a new issue if more appropriate.
