### ISSUE TITLE
problem with dockerfile + tar command

### ISSUE THREAD

**Issue by jmccormick2001** [containers/buildah#1888]
**Description**

I'm seeing a socket not supported issue when trying to build with a Dockerfile
that uses the tar command.

**Steps to reproduce the issue:**
1. use the Dockerfile in this Issue
2.
3.
Example Dockerfile and Makefile are located here:

https://github.com/jmccormick2001/rq

Note that the Makefile.docker works as I'd expected but want to get this working with buildah
if possible.

thanks!

**Describe the results you received:**
02", "/rqlite/file/data"]
STEP 12: COMMIT jmccormick2001/rqlite:v0.0.1
ERRO[0008] Can't add file /var/lib/containers/storage/overlay/5b71ff729385b07dd56b0c6a580d86d950fdccbdcfdbd02bab73fa4624543174/diff/var/cache/yum/metadata/ubi-8-appstream-8-x86_64/gpgdir/S.gpg-agent to tar: archive/tar: sockets not supported 
ERRO[0008] Can't add file /var/lib/containers/storage/overlay/5b71ff729385b07dd56b0c6a580d86d950fdccbdcfdbd02bab73fa4624543174/diff/var/cache/yum/metadata/ubi-8-appstream-8-x86_64/gpgdir/S.gpg-agent.browser to tar: archive/tar: sockets not supported 

**Describe the results you expected:**
would like to see it work with tar command if possible.

**Output of `rpm -q buildah` or `apt list buildah`:**
```
buildah-1.9.0-2.el7.centos.x86_64

```

**Output of `buildah version`:**

```
Version:         1.9.0
Go Version:      go1.10.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Wed Dec 31 18:00:00 1969
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
jeffmc@doppio114 ~/projects/rq> cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

**Output of `uname -a`:**

```
Linux doppio114 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# mountopt specifies extra mount options used when mounting the thin devices.
# mountopt = ""

# use_deferred_removal Marking device for deferred removal
# use_deferred_removal = "True"

# use_deferred_deletion Marking device for deferred deletion
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by rhatdan** [comment]
Can you move the sockets to a tmpfs?

Are you running buildah rootless or as root?

@giuseppe any idea why this would work in Docker on overlay but not on Buildah?

**Comment by jmccormick2001** [comment]
sudo --preserve-env buildah bud -f ./docker/Dockerfile -t jmccormick2001/rqlite:v0.0.1 ./docker

thanks, I'm running it like above.

**Comment by nalind** [comment]
The error's being produced when we attempt to commit an image where one of the layers will include a socket.  I think this was fixed as of #1785, so 1.11.0 or later should handle it correctly.

**Comment by jmccormick2001** [comment]
I built locally and still get the same error...

jeffmc@doppio114 ~/projects/rq> make rqlite-image
sudo --preserve-env buildah bud -f ./docker/Dockerfile -t jmccormick2001/rqlite:v0.0.1 ./docker
STEP 1: FROM registry.access.redhat.com/ubi8/ubi-minimal
STEP 2: MAINTAINER Jeff McCormick
STEP 3: ENV RQLITE_VERSION=4.5.0
STEP 4: RUN microdnf install curl gzip tar

(process:1): librhsm-WARNING **: 15:23:47.499: Found 0 entitlement certificates

(process:1): librhsm-WARNING **: 15:23:47.500: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Package                                                 Repository          Size
Installing:                                                                     
 gzip-1.9-4.el8.x86_64                                  ubi-8-baseos    170.0 kB
 tar-2:1.30-4.el8.x86_64                                ubi-8-baseos    858.4 kB
Transaction Summary:
 Installing:        2 packages
 Reinstalling:      0 packages
 Upgrading:         0 packages
 Removing:          0 packages
 Downgrading:       0 packages
Downloading packages...
Running transaction test...
Installing: tar;2:1.30-4.el8;x86_64;ubi-8-baseos
Installing: gzip;1.9-4.el8;x86_64;ubi-8-baseos
Complete.
STEP 5: RUN curl -L https://github.com/rqlite/rqlite/releases/download/v${RQLITE_VERSION}/rqlite-v${RQLITE_VERSION}-linux-amd64.tar.gz -o rqlite-v${RQLITE_VERSION}-linux-amd64.tar.gz &&  tar xvfz rqlite-v${RQLITE_VERSION}-linux-amd64.tar.gz &&  cp rqlite-v${RQLITE_VERSION}-linux-amd64/rqlited /bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   622    0   622    0     0   2692      0 --:--:-- --:--:-- --:--:--  2692
100 8898k  100 8898k    0     0  5503k      0  0:00:01  0:00:01 --:--:-- 6471k
rqlite-v4.5.0-linux-amd64/
rqlite-v4.5.0-linux-amd64/rqlite
rqlite-v4.5.0-linux-amd64/rqlited
STEP 6: RUN mkdir -p /rqlite/file
STEP 7: VOLUME /rqlite/file
STEP 8: EXPOSE 4001 4002
STEP 9: ADD docker-entrypoint.sh /bin/docker-entrypoint.sh
STEP 10: ENTRYPOINT ["docker-entrypoint.sh"]
STEP 11: CMD ["rqlited", "-http-addr", "0.0.0.0:4001", "-raft-addr", "0.0.0.0:4002", "/rqlite/file/data"]
STEP 12: COMMIT jmccormick2001/rqlite:v0.0.1
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-appstream-8-x86_64/gpgdir/S.gpg-agent to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-appstream-8-x86_64/gpgdir/S.gpg-agent.browser to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-appstream-8-x86_64/gpgdir/S.gpg-agent.extra to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-appstream-8-x86_64/gpgdir/S.gpg-agent.ssh to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-baseos-8-x86_64/gpgdir/S.gpg-agent to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-baseos-8-x86_64/gpgdir/S.gpg-agent.browser to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-baseos-8-x86_64/gpgdir/S.gpg-agent.extra to tar: archive/tar: sockets not supported 
ERRO[0007] Can't add file /var/lib/containers/storage/overlay/2470b4c9eb3abed34a2e8cdcf839e7655a13679e329141f52858601ba49aa92d/diff/var/cache/yum/metadata/ubi-8-baseos-8-x86_64/gpgdir/S.gpg-agent.ssh to tar: archive/tar: sockets not supported 
Getting image source signatures
Copying blob d8e1f35641ac skipped: already exists
Copying blob b6f081e4b2b6 skipped: already exists
Copying blob a05df6ffa3ec done
Copying config f9775a7bde done
Writing manifest to image destination
Storing signatures
f9775a7bde390ee9ea5621418dded87c13f6b81a61a73a103cd924af4d48238d
sudo --preserve-env buildah push jmccormick2001/rqlite:v0.0.1 docker-daemon:jmccormick2001/rqlite:v0.0.1
Getting image source signatures
Copying blob d8e1f35641ac done
Copying blob b6f081e4b2b6 done
Copying blob a05df6ffa3ec done
Copying config f9775a7bde done
Writing manifest to image destination
Storing signatures
Successfully pushed jmccormick2001/rqlite:v0.0.1@sha256:7f47f7bc922eaff295d7d095bf5514339cdb1692c9e224479d97aaee7641ae2f
docker tag docker.io/jmccormick2001/rqlite:v0.0.1  jmccormick2001/rqlite:v0.0.1
jeffmc@doppio114 ~/projects/rq>

**Comment by nalind** [comment]
> I built locally and still get the same error...

Hmm, my test didn't have those, but that error message still gets produced when we try to add the socket to an archive, and fixing it doesn't look like it's to be as simple as I'd have hoped.  The quickest workaround is probably to add a "&& microdnf clean all" to the end of the RUN command that installs curl, gzip, and tar.

**Comment by jmccormick2001** [comment]
thanks, that fixes it.

**Comment by nalind** [comment]
Yes, I think we should keep this one open.

**Comment by rhatdan** [comment]
@nalind @giuseppe @TomSweeneyRedHat @jmccormick2001 @vrothberg Not sure what we do with this one?

**Comment by nalind** [comment]
I attempted to add a conformance test for this, but I'm finding it difficult to reproduce at this point.  Attempting to use `tar` to archive a listening socket created by `nc -U -l` in order to get something we can ADD in a Dockerfile, tar skips it with a `tar: socket-item: socket ignored` message.  `docker build` from 19.03 ignores a socket in a build context with a `Can't add file /tmp/buildcontext/socket-item to tar: archive/tar: sockets not supported` error.

Digging through the standard library, it looks like support for sockets in archives was dropped in Go 1.9, so I don't think a recent version of `docker build` works the way it did when this was first opened.

**Comment by rhatdan** [comment]
I am going to close, since we have a workaround and are not sure that it still works on Dockre.

**Comment by nmvega** [comment]
Hello Friends:

I'm facing this same issue. Although the build completes, these errors are concerning:



```
root# buildah bud --tag acme/acme-base:1.0 -f ./Dockerfile .
[ ... snip ... ]
STEP 22: EXPOSE 8888 5000
STEP 23: ENTRYPOINT ["tini", "-g", "--"]
STEP 24: CMD ["start-singleuser.sh"]
STEP 25: USER ${NB_UID}
STEP 26: COMMIT acme/acme-base:1.0
ERRO Can't add file /var/lib/containers/storage/overlay/93faf84ea2f22584f0d78c6988ed1daf708d29135ee20daf8f367c600c1fb688/diff/run/user/0/gnupg/d.jxpei9urjn64m79npr8ybp1f/S.gpg-agent to tar: archive/tar: sockets not supported 
ERRO Can't add file /var/lib/containers/storage/overlay/93faf84ea2f22584f0d78c6988ed1daf708d29135ee20daf8f367c600c1fb688/diff/run/user/0/gnupg/d.jxpei9urjn64m79npr8ybp1f/S.gpg-agent.browser to tar: archive/tar: sockets not supported 
ERRO Can't add file /var/lib/containers/storage/overlay/93faf84ea2f22584f0d78c6988ed1daf708d29135ee20daf8f367c600c1fb688/diff/run/user/0/gnupg/d.jxpei9urjn64m79npr8ybp1f/S.gpg-agent.extra to tar: archive/tar: sockets not supported 
ERRO Can't add file /var/lib/containers/storage/overlay/93faf84ea2f22584f0d78c6988ed1daf708d29135ee20daf8f367c600c1fb688/diff/run/user/0/gnupg/d.jxpei9urjn64m79npr8ybp1f/S.gpg-agent.ssh to tar: archive/tar: sockets not supported 
Getting image source signatures
Copying blob a85e681ee93d skipped: already exists  
Copying blob dca7f50146e4 skipped: already exists  
Copying blob a77258de1464 skipped: already exists  
Copying blob c9a61ffc5e8c skipped: already exists  
Copying blob 122aa065b2be done  
Copying config a5cde60a21 done  
Writing manifest to image destination
Storing signatures
--> a5cde60a219
a5cde60a219e2d6cf9b29ba4a7bb88c71e2d5b0ea42e28949ec3dae534255c8f

root#
```
Here is some information for my case:

```
root# buildah version
Version:         1.19.8
Go Version:      go1.15.8
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.2
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64


root# buildah info
{
    "host": {
        "CgroupVersion": "v2",
        "Distribution": {
            "distribution": "fedora",
            "version": "33"
        },
        "MemFree": 50168135680,
        "MemTotal": 67374002176,
        "OCIRuntime": "crun",
        "SwapFree": 4294963200,
        "SwapTotal": 4294963200,
        "arch": "amd64",
        "cpus": 12,
        "hostname": "vps20",
        "kernel": "5.11.10-200.fc33.x86_64",
        "os": "linux",
        "rootless": false,
        "uptime": "44h 43m 8.69s (Approximately 1.83 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 1
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay.mountopt=nodev"
        ],
        "GraphRoot": "/var/lib/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "true",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 2
        },
        "RunRoot": "/run/containers/storage"
    }
}
```

**Comment by TomSweeneyRedHat** [comment]
@nmvega What is the context directory that you're running the build in.  Are there any sockets in it?  This smells a bit like: https://stackoverflow.com/questions/56215440/docker-build-error-archive-tar-sockets-not-supported/56216100

**Comment by nmvega** [comment]
Hi @TomSweeneyRedHat
It's a regular subdirectory under my home directory. 

Looking at the `Stackoverflow` comment that you mentioned, I can check if `./rootfs.d/` tree happens to have any `socket` files in it, but I doubt so.

**Comment by rhatdan** [comment]
Looks like the acme image imbedded some sockets within it.
