### ISSUE TITLE
buildah from, with error, leaks mounts

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#1991]
`buildah from` seems to mount a tmpfs working directory. On success, this is unmounted. On failure, it is left behind on the system:
```
# mkdir -p /tmp/aaa/root
# buildah --root /tmp/aaa/root --storage-driver overlay from --pull=false alpine
[ lots of errors, expected ]

# mount|grep aaa
tmpfs on /tmp/aaa/root/overlay type tmpfs (rw,nosuid,nodev,seclabel)   <<< not expected
```
This causes failures on gating tests when `STORAGE_DRIVER=overlay` because the temporary working directories cannot be cleaned up.

buildah-1.11.4-2.fc30.x86_64 and buildah-1.11.4-2.module+el8.2.0+4595+e1e23178.x86_64

**Comment by rhatdan** [comment]
@edsantiago I believe this is fixed, I was not able to recreate it.  Reopen if I am mistaken.

**Comment by edsantiago** [comment]
No, it's not fixed, but I don't have privs to reopen.

Looks like at some point in time, `--pull=false` broke (or changed behavior without actually documenting that). The new recipe is:
```console
# buildah --root /tmp/aaa/root --storage-driver overlay from --pull-never alpine
[lots of errors]
# mount|grep aaa
tmpfs on /tmp/aaa/root/overlay type tmpfs (rw,nosuid,nodev,seclabel)
```

buildah-1.15.0-1.fc32

I'm kind of concerned about this `--pull=false` change. I'm astonished there's no test for it. Should I file an issue, or is this really some sort of new desired behavior?

@rhatdan, please reopen.

**Comment by TomSweeneyRedHat** [comment]
Taking one off @rhatdan's illicit closure list!  ;^)

**Comment by rhatdan** [comment]
Great @edsantiago thanks.

**Comment by vrothberg** [comment]
> I'm kind of concerned about this --pull=false change. I'm astonished there's no test for it. Should I file an issue, or is this really some sort of new desired behavior?

If the behavior has changed, please open an issue. It screams for tests.
