### ISSUE TITLE
`repository name must be canonical` when `buildah` is > `1.22.0`

### ISSUE THREAD

**Issue by rcny** [containers/buildah#3500]
**Description**

`buildah login docker.io/user` errors with

```
parse reference from "docker.io/user": repository name must be canonical
```

after updating to `1.22.3` from `1.22.0`. `buildah login docker.io/user` worked before, had to change to `buildah login docker.io` to make it work again.

Most possibly this behavior change was introduced [here](https://github.com/containers/buildah/commit/2d1b0f84f0d70a836fe9d1aaf85a5738728fb217).

**Steps to reproduce the issue:**
1. Install `buildah 1.22.3`
2. `echo "foobar" | buildah login --username "user" --password-stdin "docker.io/user"` (use proper creds)

**Describe the results you received:**

```
parse reference from "docker.io/user": repository name must be canonical
```

**Describe the results you expected:**

`Login Succeeded!`

**Comment by vrothberg** [comment]
Thanks for reaching out, @rcny!  @saschagrunert PTAL

**Comment by saschagrunert** [comment]
The issue is that `docker.io/user` will fail on `ParseNamed()` here:
https://github.com/containers/buildah/blob/58a16f97689cc96b1a69a03d773c4399413f8854/vendor/github.com/containers/image/v5/docker/reference/reference.go#L246-L248

A valid input would be `docker.io/library/user`, which should work. 

Working on a fix in https://github.com/containers/common/pull/757

**Comment by rhatdan** [comment]
I believe this is fixed now, closing. Reopen if I am mistaken.

**Comment by vrothberg** [comment]
It is not fixed, reopening.  I really want this to work before we cut Podman 4.0.

**Comment by vrothberg** [comment]
This has been fixed in the meantime.
