### ISSUE TITLE
buildah bud .dockerignore functionality missing

### ISSUE THREAD

**Issue by kbaegis** [containers/buildah#699]
**Description**

buildah bud needs to check the .dockerignore file in the build directory to exclude files and directories from the build process.

**Comment by pixdrift** [comment]
Thanks for the report @kbaegis. Do you have a basic reproducer/example of this we can use as an example?

**Comment by kbaegis** [comment]
Documented here: https://docs.docker.com/engine/reference/builder/#dockerignore-file

I evidently didn't try writing one in my new toolchain. This might already have been implemented; testing now.

**Comment by kbaegis** [comment]
Yeah, it works. :)

**Comment by TomSweeneyRedHat** [comment]
Phew!

**Comment by adambkaplan** [comment]
@TomSweeneyRedHat this seems to have been broken since May.

Steps to reproduce:

1. Clone https://github.com/adambkaplan/dockerignore.git
2. Build image with buildah (`buildah bud ...`)

Expected result:
* LICENSE and README.md should not be listed during the build process

Actual result:
* LICENSE and README.md are include in the final image.

**Comment by TomSweeneyRedHat** [comment]
Thanks for the heads up @adambkaplan, I'll reopen this then.

**Comment by rhatdan** [comment]
@kbaegis @TomSweeneyRedHat is this fixed now?

**Comment by TomSweeneyRedHat** [comment]
Not fixed that I know of.

**Comment by cjsin** [comment]
The commit which supposedly fixed this, b1d14767f32f59e544f3e6522208ef4be31a9675 
seems to be included in release 1.8.2
however this is still not working for me with version 1.8.2 (RPM package from fedora 29)

Example:

```
$> buildah --version
buildah version 1.8.2 (image-spec 1.0.0, runtime-spec 1.0.0)
```

example / test repository:

```
$> git clone https://github.com/adambkaplan/dockerignore.git
Cloning into 'dockerignore'.. <extra output snipped>
```

dockerfile contents:

```
FROM quay.io/quay/busybox:latest

ADD . /tmp/src
RUN ls -l /tmp/src

ENTRYPOINT ["/bin/bash"]

```

dockerignore contents:

```
$> cat .dockerignore 
LICENSE
```

buildah bud output:

```
$> cd dockerignore/
buildah bud .
STEP 1: FROM quay.io/quay/busybox:latest
Getting image source signatures
Copying blob f0a98344d604 done
Copying blob 48341aa39e69 done
Copying blob 3eecc807f63d done
Copying blob 3eecc807f63d done
Writing manifest to image destination
Storing signatures
STEP 2: ADD . /tmp/src
STEP 3: RUN ls -l /tmp/src
total 24
-rw-rw-r--    1 root     root            94 May 28 11:47 Dockerfile
-rw-rw-r--    1 root     root         11357 May 28 11:47 LICENSE
-rw-rw-r--    1 root     root            55 May 28 11:47 README.md
-rw-rw-r--    1 root     root            12 May 28 11:47 source.txt
  <extra output snipped>
```

As can be seen from the output, the LICENSE file was still ADDed in

**Comment by TomSweeneyRedHat** [comment]
@kbaegis thanks for the follow up, I'll reopen this.
@QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
Ooops, I mean @cjsin thanks for the follow up, back to the tea cup for me!

**Comment by QiWang19** [comment]
I can't regenerate this issue. :thinking: 
besides, the .dockerignore under github.com/adambkaplan/dockerignore also excludes the README.md

```
LICENSE
*.md
```

**Comment by iNecas** [comment]
I can confirm buildah 1.8.2 on Fedora 29 handles `.dockerignore` just fine :+1:

**Comment by rhatdan** [comment]
@kbaegis What version of buildah are you using?

**Comment by QiWang19** [comment]
@rhatdan this issue was reopened with buildah version 1.8.2 (RPM package from fedora 29)

**Comment by rhatdan** [comment]
So is this bug fixed or not?

**Comment by iNecas** [comment]
It's definitely fixed for me

**Comment by etsauer** [comment]
Hey all,

This issue seems to have resurfaced in 1.11.4 on F31:

```
$ git clone https://github.com/adambkaplan/dockerignore.git
Cloning into 'dockerignore'...
remote: Enumerating objects: 9, done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 9
Unpacking objects: 100% (9/9), done.

$ cd dockerignore/

$ cat Dockerfile 
FROM quay.io/quay/busybox:latest

ADD . /tmp/src
RUN ls -l /tmp/src

ENTRYPOINT ["/bin/bash"]
[esauer 🎩︎dockerignore] (master)$ cat .dockerignore 
LICENSE
*.md[esauer 🎩︎dockerignore] (master)$ LICENSE^C

$ ls -a
.  ..  Dockerfile  .dockerignore  .git  LICENSE  README.md  source.txt

$ buildah bud
STEP 1: FROM quay.io/quay/busybox:latest
Getting image source signatures
Copying blob 48341aa39e69 done
Copying blob f0a98344d604 done
Copying blob 3eecc807f63d done
Copying blob 3eecc807f63d done
Writing manifest to image destination
Storing signatures
STEP 2: ADD . /tmp/src
STEP 3: RUN ls -l /tmp/src
2019-12-13T21:30:18.000135407Z: cannot configure rootless cgroup using the cgroupfs manager
total 24
-rw-rw-r--    1 root     root            94 Dec 13 21:29 Dockerfile
-rw-rw-r--    1 root     root         11357 Dec 13 21:29 LICENSE
-rw-rw-r--    1 root     root            55 Dec 13 21:29 README.md
-rw-rw-r--    1 root     root            12 Dec 13 21:29 source.txt
STEP 4: ENTRYPOINT ["/bin/bash"]
STEP 5: COMMIT
Getting image source signatures
Copying blob f62439784159 skipped: already exists
Copying blob de4246eaeb69 skipped: already exists
Copying blob 35725853fd5a skipped: already exists
Copying blob de4246eaeb69 skipped: already exists
Copying blob 02d299e76fca done
Copying config da98a3d5bf done
Writing manifest to image destination
Storing signatures
da98a3d5bffcd321e0e7f0c39d20407281ef1985ee331baa2b29f713a26bcb5e

$ buildah version
Version:         1.11.4
Go Version:      go1.13.1
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Comment by mhenrixon** [comment]
I have the exact same problem in:

```shell
buildah version 1.19.3 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
``

**Comment by TomSweeneyRedHat** [comment]
I'm going to reopoen this one.

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 can you take a quick peak please?

**Comment by rhatdan** [comment]
I just ran the test and it works for me on Fedora 33.

```
$ git clone https://github.com/adambkaplan/dockerignore.git
Cloning into 'dockerignore'...
remote: Enumerating objects: 9, done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 9
Receiving objects: 100% (9/9), 5.05 KiB | 5.05 MiB/s, done.
$ cd dockerignore/
$ ls
Dockerfile  LICENSE  README.md  source.txt
$ buildah bud .
STEP 1: FROM quay.io/quay/busybox:latest
Getting image source signatures
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob 9c075fe2c773 done  
Copying blob ee780d08a5b4 done  
Writing manifest to image destination
Storing signatures
STEP 2: ADD . /tmp/src
STEP 3: RUN ls -l /tmp/src
total 8
-rw-rw-r--    1 root     root            94 Feb  2 15:16 Dockerfile
-rw-rw-r--    1 root     root            12 Feb  2 15:16 source.txt
STEP 4: ENTRYPOINT ["/bin/bash"]
STEP 5: COMMIT
Getting image source signatures
Copying blob c632c18da752 skipped: already exists  
Copying blob b24b2272e25f skipped: already exists  
Copying blob d31465522116 done  
Copying config 6cc5d43347 done  
Writing manifest to image destination
Storing signatures
--> 6cc5d433476
6cc5d4334765c5f715840921f71e9e5b67060c63f3433827e7bed381dba46252
```
```
$ buildah version
Version:         1.19.3
Go Version:      go1.15.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.1
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Comment by mhenrixon** [comment]
I forgot to mention, I am installing the package in Alpine 3.12

**Comment by rhatdan** [comment]
And you are seeing difference from what I showed on Fedora, with the same buildah?

**Comment by mhenrixon** [comment]
@rhatdan it isn't that easy for me to test because I can't run the build in alpine locally at all even after setting isolation to chroot and creating the necessary config files. I can use buildah installed with the alpine package manager but I had to make a custom install for fuse-overlay (the alpine package wasn't working).

I can't seem to make buildah work inside docker for mac:

> [root@445b71c80d32 app]# buildah bud .
> Error during unshare(CLONE_NEWUSER): Operation not permitted
> ERRO error parsing PID "": strconv.Atoi: parsing "": invalid syntax
> ERRO (unable to determine exit status)

Not sure what I need to do but I guess I have to fiddle with the docker for mac docker container somehow.

**Comment by rhatdan** [comment]
This is because of Docker seccomp rules.

docker run --security-opt seccomp=unconfined ...

**Comment by rhatdan** [comment]
I believe we are now consistent so please reopen if you find a bug and have a reproducer.

**Comment by cmacq2** [comment]
buildah's `.dockerignore` implementation does not seem to be entirely equivalent to that of docker, specifically "ignore everything except these few file" type scenario's do not work as expected.

Examples

## Ignoring everything via `.dockerignore`
```
*
```
Expected behaviour from `docker build -t test:latest .`: cryptic error because the `Dockerfile`  itself cannot be found in the context (it is ignored). `buildah bud -t test:latest .`: builds an image.

## Ignoring everything except a few whitelisted files in `.dockerignore`
```
*
!Dockerfile
!README.md
```
Expected behaviour from `docker build -t test:latest .`: works, can `COPY README.md /README.md` in `Dockerfile`.
`buildah bud --log-level debug -t test:latest .` yields the following error:
```
STEP 3: COPY README.md /README.md
DEBU COPY []string(nil), imagebuilder.Copy{FromFS:false, From:"", Src:[]string{"README.md"}, Dest:"/README.md", Download:false, Chown:""}
DEBU Skipping excluded path: README.md
DEBU error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[README.md /README.md] Flags:[] Attrs:map[] Message:COPY README.md /README.md Original:COPY README.md /README.md}: error adding sources [/path/to/project/README.md]: no items matching glob "/path/to/project/README.md" copied (1 filtered out): no such file or directory
error building at STEP "COPY README.md /README.md": error adding sources [/path/to/project/README.md]: no items matching glob "/path/to/project/README.md" copied (1 filtered out): no such file or directory
```

This is with `buildah --version`
```
buildah version 1.19.6 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```
On Debian (`/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by TomSweeneyRedHat** [comment]
reopening, @rhatdan back at ya

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
I can't reproduce that second case here, neither with 1.19.6 nor the current development tip.

**Comment by rhatdan** [comment]
@cmacq2 ^^

**Comment by brancz** [comment]
Just ran into this as well. Not sure if it helps, but I put together a small example based on @adambkaplan's repo. For what it's worth not all ignore functionality is broken, but only the "ignore all but X" cases. The example: https://github.com/brancz/dockerignore

**Comment by rhatdan** [comment]
This is fixed in the current release.

**Comment by brancz** [comment]
I can still reproduce it with 1.21.0 using the repo that I linked to above. Note that the remaining issue is _not_ that all excludes don't work, it's the "exclude all but X" syntax that doesn't work:

```
# Ignore everything
**

# Allow only source.txt
!./source.txt
```

**Comment by rhatdan** [comment]
Please open a new issue for this .
