### ISSUE TITLE
Build/Push/Pull via HTTP Proxy

### ISSUE THREAD

**Issue by maxmeyer** [containers/buildah#765]
**Description**

**Steps to reproduce the issue:**
1. `sudo buildah build-using-dockerfile --file files/latest/Dockerfile` 

**Describe the results you received:**

Installing packages by `apk add` hangs with no progress

**Describe the results you expected:**

Installing packages works without any build args passed to `buildah` - something similar to https://docs.docker.com/network/proxy/

**Possible solutions**

* Use `--build-args`
* Use config file

If you need to pass proxy configuration via `--build-args` you need to make your build scripts of project XY aware of the HTTP*/http*-variables thus make them depend on the developers environment. So I would prefer to have a config file.

*Example A*:

`bin/build-no-config`:
~~~
#!/usr/bin/env sh

sudo buildah build-using-dockerfile --file files/latest/Dockerfile --build-arg HTTP_PROXY=http://10.0.2.15:3128 
~~~

*Example A*:

`bin/build-with-config`:
~~~
#!/usr/bin/env sh

sudo buildah build-using-dockerfile --file files/latest/Dockerfile
~~~

`~/.buildah/config.json`:
~~~
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://10.0.2.15:3128"
   }
 }
}
~~~

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.0-1.git1ab80bc.fc28.x86_64
```

**Output of `buildah version`:**

```
Version:       1.0
Go Version:    go1.10.1
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    1ab80bc
Built:         Mon May  7 16:01:02 2018
OS/Arch:       linux/amd64

```

**Output of `cat /etc/*release`:**

```
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
Linux host.example.com 4.16.13-300.fc28.x86_64 #1 SMP Wed May 30 14:31:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
We already have a fix for this in Master. Should be in the buildah 1.1 release.

**Comment by rhatdan** [comment]
Seems like a feature of containers/image.
@mtrmac PTAL

**Comment by vrothberg** [comment]
@rhatdan I think this is something that can be achieved with sysregistriesv2 package in containers/image. I am currently preparing a fix for it as discussed in https://github.com/projectatomic/libpod/issues/721. However, push-mirrors is something being discussed in the dist-spec at the moment and will take a while afaik.

**Comment by mtrmac** [comment]
Looking at `c/image/pkg/tlsclientconfig.NewTransport`, the docker/distribution client should already be transparently using the standard Golang environment variables (https://golang.org/pkg/net/http/#ProxyFromEnvironment ); at the very least, it does not ignore the variables at all:
```
$ http_proxy=http://foo.bar ./skopeo --insecure-policy --override-os linux inspect docker://busybox
FATA[0000] pinging docker registry returned: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup foo.bar: no such host 
```

So, if that works, there should already be _a_ way to make things work.

---

As for whether it makes more sense as an environment variable, as a system-wide configuration in `sysregistriesv2`, or as a per-user configuration in `~/$whatever/config.json`, all three seem problematic to me for one reason or another from a quick look. But I’ve never really used proxies to a significant extent, so I’d rather defer to this to someone with practical experience.

---

> However, push-mirrors is something being discussed in the dist-spec at the moment and will take a while afaik.

As in, an alternate distribution server to use instead of the named one? That could be useful, but it’s orthogonal to HTTP proxy support (where the proxy does not understand the docker/distribution protocol in any way, but the site may require all connections to go through that proxy).

**Comment by mtrmac** [comment]
> As for whether it makes more sense as an environment variable, as a system-wide configuration in sysregistriesv2, or as a per-user configuration in ~/$whatever/config.json, all three seem problematic to me for one reason or another from a quick look. 

Whichever configuration mechanism ends up being used, I do agree that this should be handled transparently with containers/image, at least by default.

**Comment by TomSweeneyRedHat** [comment]
@maxmeyer is this still problematic for you with Buildah v1.2?  I think it may have been fixed there, but would like your confirmation if possible.

**Comment by mtrmac** [comment]
I’m sorry, it seems I have not read the original issue carefully enough; it is _not_ related to c/image _using_ a proxy, it is about _passing the proxy configuration into the build environment_.

That’s fundamentally a buildah design decision; c/image may be involved if the design decision were to record the default-injected proxies in something like `~/.docker/config.json` (… FWIW the `…/containers/auth.json` name is problematic).

**Comment by rhatdan** [comment]
@mtrmac Do you have  a suggested solution?

**Comment by mtrmac** [comment]
> @mtrmac Do you have a suggested solution?

Both proposals in the original issue description are reasonable in principle; the CLI argument option would be easier to implement (avoids having to introduce a buildah config file), but a bit less convenient. I don’t think at this point, when nobody is implementing either of them, it makes much sense to bikeshed over the exact spelling etc.

**Comment by mtrmac** [comment]
> I don’t think at this point, when nobody is implementing either of them, it makes much sense to bikeshed over the exact spelling etc.

… whether to use the data in `~/.docker/config.json` at all, and if so, what would be the proposed alternative config file, should probably be discussed before implementing it, though. I don’t really have a strong opinion on these questions, anyway.

**Comment by rhatdan** [comment]
I would not be opposed to having a ~/.contianers/config.json (Or some better format that buildah/podman could share.  And have a /etc/containers/config.* that programs running as root could share, including CRI-O.  Should this be implemented in containers/image though?

**Comment by mtrmac** [comment]
> I would not be opposed to having a ~/.contianers/config.json (Or some better format that buildah/podman could share. … Should this be implemented in containers/image though?

That rather depends on what all ends up in there… and maybe on the dependency graph, so that there are no cycles (between specific subpackages at least; and maybe between repos as a whole).

`c/image` will probably never care about proxy configuration to pass into containers, so placing the code to deal with _that_ inside `c/image` would be a bit surprising. OTOH, placing a shared subpackage inside `c/image/pkg` costs nothing, so if it improved the dependency graph, sure. (Maybe we would eventually want something like `GitHub.com/containers/shared-infrastructure`, but using `c/image/pkg` in the meantime seems acceptable, even if not perfect.)

My primary question about `containers/config.json` is whether it would that be completely independent of `containers/auth.json` (which `c/image` does need to understand), or maybe replace it? If `containers/config.json` were to replace `containers/auth.json`, `c/image` would need to understand it, at least enough to read the credentials out of there — and then placing the code to read all of it inside `c/image/pkg` could be the simplest implementation.

**Comment by rhatdan** [comment]
@nalind @mrunalp @jwhonce @vrothberg @mheon  WDYT?

**Comment by rhatdan** [comment]
Well the package we are dumping them into is called containers-common

**Comment by rhatdan** [comment]
I would rather have one config file for this, Perhaps registryconfig.json?

**Comment by rhatdan** [comment]
@vrothberg This seems to be in an area you have been investigating.

**Comment by vrothberg** [comment]
> @vrothberg This seems to be in an area you have been investigating.

Sure, I will look into it next week.

**Comment by vrothberg** [comment]
Alright, I think the initial request turned into something more general:

#### How shall the libraries/tools treat proxies?

Currently, the env variables work for distribution, and when running a container but apparently not when building one. A quick fix could be to inject those by default into the build.

Another (orthogonal) question is:

#### How can we make proxies configurable?

I suggest to make a `proxies.conf` that can be consumed by all tools. Following up on issues mentioned above, I suggest putting the code for parsing the `proxies.conf` into `containers/image/pkg/proxy` (or sth similar). The logic should be fairly simple, for instance:

1. Get the env variables.
2. Parse the config and, if specified, overwrite the variables.
3. Return them as a `map[string]string`.

Build-args would still overwrite them, which should lift the tools to align with what Docker offers.

@mheon @mtrmac @rhatdan @runcom @TomSweeneyRedHat @umohnani8 WDYT? Am I missing something?

**Comment by mtrmac** [comment]
If we were injecting the environment variables by default, would we even need the config file? I have very little experience with living behind a mandatory proxy, but still, it seems undesirable to have the proxy configuration in config files all over the place — there should ideally be _one_ place within the whole OS defining the proxy, shouldn’t it?

Sure, _if_ we do need a container-specific config file, a single one shared by all container tools is definitely better than set of  separate files, one each for Podman/Buildah/CRI-O/… .  But “a single config file for container tools” still seems like one file too many.

Again, I have very little practical experience, and the above might be completely impractical, or wrong in some other way.

---

WRT the subpackage API:

_If_ we had a separate config file, and a subpackage to parse it, I think it should _primarily_ provide an API to return (or modify)? a `http.Transport` that works with the proxies as configured, so that callers don’t have to deal with the actual structure of the configuration at all; an API to return the underlying proxy configuration might be necessary (e.g. so that they can be injected into buildah-executed processes, as suggested elsewhere here), but it should not be the way _most_ users interact with the subpackage.

**Comment by vrothberg** [comment]
@mtrmac, I agree with your line of argument but I fear that the expectations are to offer something similar to how Docker makes the proxy configurable. In contrast to Docker's `config.json` we don't have one, central, shared config file for common options among those tools but multiple specialised ones, I think we should add (yet another) one `proxies.conf`.

**Comment by rhatdan** [comment]
Should this be added to registries.conf?

**Comment by vrothberg** [comment]
> Should this be added to registries.conf?

I have no objections against putting this into the registries.conf. @runcom, WDYT?

**Comment by rhatdan** [comment]
@vrothberg Looks like https://github.com/containers/image/pull/537 is languishing?

**Comment by mtrmac** [comment]
@rhatdan This has ultimately very little to do with proxy support in c/image (and with that c/image PR in particular); the goal here is to pass a proxy setting from the caller’s environment into buildah-managed containers, a concern ~entirely local to buildah, once _some_ way to pass those settings is defined.

That way is currently environment variables; if we want to change that, fine, but that’s yet third mostly unrelated idea.

**Comment by rhatdan** [comment]
Doesn't Just setting the environment variables just work?

**Comment by vrothberg** [comment]
We could have configure the proxies for the host (Buildah, Podman, and friends) and for the containers separately but in the same config.

**Comment by rhatdan** [comment]
Why is that any better then just dropping a enfironment file in /etc/profiles.d.

I would like to avoid a configuration file if possible, or we put it into registries.conf.

**Comment by jamescassell** [comment]
The universal way of setting proxy config is through the standard lowercase environment variables... as long as those are honored, most cases will be covered.

**Comment by jamescassell** [comment]
Is there a way to include a list of environment variables that are always passed thru to the container?  That would solve this issue, and allow certain other use cases, as well.

I'd propose a default list of:
```
http_proxy
https_proxy
ftp_proxy
no_proxy
```
and maybe the upper case versions of those as well

**Comment by rhatdan** [comment]
--envfile

**Comment by jamescassell** [comment]
```
buildah from --envfile=envfile centos
unknown flag: --envfile
`

**Comment by rhatdan** [comment]
Yes I was thinking podman not buildah sorry.

So you want these environment variables set for when you are doing your builds and RUNs but not for the final container artefact.

**Comment by rhatdan** [comment]
How about if we added a field --httpproxy to buildah bud and run to pass in the http proxy environment variables to the container?
@nalind @vrothberg @mtrmac WDYT?

**Comment by jamescassell** [comment]
I think it would make more sense to detect the presence of `*_proxy` environment variables and automatically inject them unless explicitly asked not to.  Folks who have these set are most likely required to pass all their connections thru the proxy to get access to the internet.  The `no_proxy` env var specifies which hosts should be accessed directly, bypassing the proxy.

**Comment by rhatdan** [comment]
That's fine, we could add the proxy switch and default to true.

**Comment by rhatdan** [comment]
@jamescassell Would you be interested in attempting to do this?

**Comment by jamescassell** [comment]
I'll take a crack at it once I get a moment, though I'm not exactly sure how soon it will be.

**Comment by jamescassell** [comment]
a quick workaround is to bind-mount a shell init file, then pass all commands thru a bash login shell like
```
export ctr=$(buildah from -v /etc/profile.d/proxy.sh:/etc/profile.d/colorgrep.sh centos)
buildah run $ctr bash -l -c 'yum -y install httpd'
```

I suppose something similar could be used for injecting RHEL subscriptions... though you'd need a cronjob to create a world-readable copy of the ssl keys

**Comment by jamescassell** [comment]
#1510 implements the functionality described in the issue description as well as https://github.com/containers/buildah/issues/765#issuecomment-482709421 by injecting proxy vars into the container if they are set for `buildah from` or `buildah bud`

@maxmeyer does this meet your need?

Nothing in #1510 attempts to change anything for push or pull

**Comment by maxmeyer** [comment]
> injecting proxy vars into the container if they are set for buildah from or buildah bud

@jamescassell Sounds good. Thanks a lot!

> Nothing in #1510 attempts to change anything for push or pull

So pushing an image via HTTP proxy to an external registry is still not possible, correct? It would be helpful to have this as well; otherwise I cannot push images to hub.docker.com.

**Comment by jamescassell** [comment]
> 
> > Nothing in #1510 attempts to change anything for push or pull
> 
> So pushing an image via HTTP proxy to an external registry is still not possible, correct? It would be helpful to have this as well; otherwise I cannot push images to hub.docker.com.

I expect that it will work today with `http_proxy` and `https_proxy` environment variables, but haven't actually tested pushing. Pulling definitely works thru a proxy.

**Comment by rhatdan** [comment]
Since we believe this is fixed, I am going to close the issue, Reopen if I am mistaken.

**Comment by handflucht** [comment]
In my understanding this is still an issue if you use apt (e.g. apt-get install) while building. The building stops if apt needs to connect to the internet and a proxy is used.

apt doesn't care about the http_proxy-variable- it needs instead a specific configuration file where the proxy-information is stored. More information here: https://askubuntu.com/a/116136/884040

Is there a possible solution or workaround for this?

**Comment by vrothberg** [comment]
> apt doesn't care about the http_proxy-variable- it needs instead a specific configuration file where the proxy-information is stored. More information here: https://askubuntu.com/a/116136/884040

This configuration file is very specific to apt. One way to tackle it would be to copy the file (in the Dockerfile) or mount it `buildah bud --volume` into the container.

@rhatdan @TomSweeneyRedHat is there a way to specify a temporary mount? What I mean by that is that files in mounted volumes are committed to the image as well. But it may be desirable to not commit those when they're only used for building.

**Comment by rhatdan** [comment]
Could we use mounts.conf on Debian/Ubuntu platforms to mount this configuration file into all containeres, like we do with the secrets files on Fedora/RHEL systems.

**Comment by vrothberg** [comment]
> Could we use mounts.conf on Debian/Ubuntu platforms to mount this configuration file into all containeres, like we do with the secrets files on Fedora/RHEL systems.

We could use that but it doesn't solve the problem that the files would be "committed" to the image. That might not be desirable at all when running the containers outside the build environment where a proxy might not be needed anymore (or another one is in place).

**Comment by rhatdan** [comment]
Files from mounts.conf do NOT get committed to the image, they are treated like bind mounts.

**Comment by vrothberg** [comment]
> Files from mounts.conf do NOT get committed to the image, they are treated like bind mounts.

They do get committed, I just re-tested it with Buildah v1.11.4. As specified paths in the mounts.conf are copied into the container, I'd argue that this behavior is correct.

**Comment by handflucht** [comment]
I just tested it on my own: files defined in mounts.conf get not committed. Please follow my commented terminal-session.

Host-system has a proxy, a dockerfile is defined which needs internet access while processing and a mounts-file is defined:
```
handflucht@local~/Desktop$ cat /etc/apt/apt.conf
Acquire::http::proxy "http://usr:pw@proxy:80/";
Acquire::https::proxy "http://usr:pw@proxy:8080/";

handflucht@local~/Desktop$ cat Dockerfile
FROM ubuntu:latest
RUN apt-get update

handflucht@local~/Desktop$ cat /etc/containers/mounts.conf.bak
/etc/apt/apt.conf:/etc/apt/apt.conf
```

Because the mounts.conf has not the correct name, the build does not work:

```
handflucht@local~/Desktop$ sudo podman build --no-cache --tag apttest .
STEP 1: FROM ubuntu:latest
STEP 2: RUN apt-get update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease                        
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) 
  [...]
W: Some index files failed to download. They have been ignored, or old ones used instead.
STEP 3: COMMIT apttest
4da212d1877fa8b2135accce4d2e6343f337e4a206b281242f4de389d8961e76
```

The mounts.conf.bak is renamed to mounts.conf and the build works:
```
handflucht@local~/Desktop$ sudo mv /etc/containers/mounts.conf.bak /etc/containers/mounts.conf
handflucht@local~/Desktop$ sudo podman build --no-cache --tag apttest .
STEP 1: FROM ubuntu:latest
STEP 2: RUN apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
[...]
Fetched 17.4 MB in 3s (6652 kB/s)                          
Reading package lists... Done
STEP 3: COMMIT apttest
2c46ac9938a50b860ebbe89ae10563012f6b9074d9730ba1330516b751060e38
```

Now lets check if the apt.conf is inside the container:
```
handflucht@local~/Desktop$ sudo podman run --rm -it  apttest /bin/sh
# cat /etc/apt/apt.conf
Acquire::http::proxy "http://usr:pw@proxy:80/";
Acquire::https::proxy "http://usr:pw@proxy:8080/";

# exit
```

Yes it is. But lets rename the mounts.conf again and recheck:

```
handflucht@local~/Desktop$ sudo mv /etc/containers/mounts.conf /etc/containers/mounts.conf.bak
handflucht@local~/Desktop$ sudo podman run --rm -it  apttest /bin/sh
# ls /etc/apt
apt.conf  apt.conf.d  auth.conf.d  preferences.d  sources.list sources.list.d trusted.gpg.d
# cat /etc/apt/apt.conf
# exit
```

So files defined in mounts.conf do not get committed to the container, but you should not forget to "disable" the mounds.conf-file before running a container. 


Thank you for your feedback, my issue has been solved by following the above example.
