### ISSUE TITLE
buildah inspect has 5 values that differ from docker inspect

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#952]
During conformance testing it was discovered:

Five items have different values: WorkingDir, OnBuild, Hostname, Labels, Cmd when doing a buildah inspect versus a docker inspect.

Per Yiqiao Pu

[1] https://github.com/ypu/buildah/tree/conformance

Buildah 1.4

**Comment by TomSweeneyRedHat** [comment]
https://jira.coreos.com/browse/RUN-70

**Comment by rhatdan** [comment]
Fixed in https://github.com/projectatomic/buildah/pull/958

**Comment by ypu** [comment]
Test with new tree. And find out the problem still exist when we set "--format docker" during the test. The pullreq effect the default value which is "--format oci" from my test.

**Comment by rhatdan** [comment]
All are still wrong?

**Comment by ypu** [comment]
Seems Hostname, Labels are fixed. Cmd in ContainerConfig is still different. But Cmd in config is the same. This is the details of test results. Only list items in Config here, ContainerConfig is similar:
With set --format=oci:

Field Name | Value in docker image | Value in buildah image
------------ | ------------- | -------------
Config:OnBuild | [] | "<nil>"
Config:Hostname | 394579f29896 | ""

With set --format=docker:

Field Name | Value in docker image | Value in buildah image
------------ | ------------- | -------------
Config:Entrypoint | "<nil>" | []
Config:Hostname | 08690ee29825 | 0ef136a841d7
Config:Volumes | "<nil>" | map[]

**Comment by rhatdan** [comment]
The hostname should be different, Since these are generated on the fly.

**Comment by rhatdan** [comment]
I don't see a difference here?

```
 docker inspect --format {{.Config.Volumes}} dan
map[]
./buildah inspect --format {{.Docker.Config.Volumes}} dan
map[]
```

**Comment by rhatdan** [comment]
Or here
```
# ./buildah inspect --format {{.Docker.Config.Entrypoint}} dan
[]
# docker inspect --format {{.Config.Entrypoint}} dan
[]
```

**Comment by ypu** [comment]
Hi @rhatdan 
Checked the image. And find if you print the value with --format {{.Config.Entrypoint}}, it will show "[]". But if you inspect the image without --format, the value will turn to "null". And also test --format {{.Config}}, it shows <nil> . So the docker inspect output seems depends on the command line flags.

**Comment by rhatdan** [comment]
We have agreement on differnces, and for the most part they match.
